#!/usr/bin/env bash
# Independent verification of tests/fixtures/dequant/*.f32.
#
# Downloads llama.cpp's ggml-quants.c / ggml-common.h (the authoritative
# reference), extracts the real `dequantize_row_*` functions into a small C
# harness compiled with clang, runs it over every fixture input block and
# compares the produced binary32 values bit-for-bit against the committed
# expectations generated by tools/ggml_reference.py.
#
# Requires: network + clang.  Usage: tools/crosscheck_dequant.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work="$root/.zig-cache/dequant-crosscheck"
mkdir -p "$work"

base="https://raw.githubusercontent.com/ggml-org/llama.cpp/master/ggml/src"
[ -f "$work/ggml-quants.c" ] || curl -fsSL "$base/ggml-quants.c" -o "$work/ggml-quants.c"
[ -f "$work/ggml-common.h" ] || curl -fsSL "$base/ggml-common.h" -o "$work/ggml-common.h"

python3 - "$work" <<'PY'
import sys, pathlib
work = pathlib.Path(sys.argv[1])
src = (work / "ggml-quants.c").read_text()

def extract(name):
    i = src.index("void %s(" % name)
    j = src.index("{", i)
    depth = 0
    for k in range(j, len(src)):
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                return src[i:k + 1]
    raise SystemExit("unterminated " + name)

names = ["q4_0", "q4_1", "q5_0", "q5_1", "q8_0", "q2_K", "q3_K", "q4_K", "q5_K", "q6_K", "q8_K"]
parts = [extract("dequantize_row_" + n) for n in names]
helper = src[src.index("static inline void get_scale_min_k4"):]
helper = helper[:helper.index("\n}\n") + 3]
(work / "extracted.c").write_text(helper + "\n\n" + "\n\n".join(parts) + "\n")
print("extracted %d reference functions" % len(parts))
PY

cat > "$work/harness.c" <<'EOF'
/* Harness: run the real ggml dequantize_row_* functions on raw fixture blocks. */
#define GGML_COMMON_DECL_C
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "ggml-common.h"

static float fp16_to_fp32(uint16_t h) {
    _Float16 f;
    memcpy(&f, &h, sizeof(h));
    return (float) f;
}
#define GGML_FP16_TO_FP32(x) fp16_to_fp32(x)
#define GGML_RESTRICT restrict

#include "extracted.c"

/* Raw (non-quantized) formats: ggml converts these with plain bit casts. */
static void dequantize_row_f32_local(const void * p, float * y, int64_t k) {
    memcpy(y, p, (size_t) k * sizeof(float));
}
static void dequantize_row_f16_local(const void * p, float * y, int64_t k) {
    const uint16_t * h = p;
    for (int64_t i = 0; i < k; i++) y[i] = fp16_to_fp32(h[i]);
}
static void dequantize_row_bf16_local(const void * p, float * y, int64_t k) {
    /* ggml: GGML_BF16_TO_FP32(x) == GGML_FP32_SET_BIASED_EXP... no; it is
       y = bitcast(u32(bits) << 16), i.e. bf16 is the top half of a float32. */
    const uint16_t * h = p;
    for (int64_t i = 0; i < k; i++) {
        const uint32_t bits = (uint32_t) h[i] << 16;
        memcpy(&y[i], &bits, 4);
    }
}

/* q8_1 has no dequantize_row_* in ggml-quants.c (it is a dot-product
   intermediate); its layout is block_q8_1 { half d; half s; int8 qs[32]; }
   and its only scale is d.  Written here straight from that definition. */
static void dequantize_row_q8_1_local(const block_q8_1 * x, float * y, int64_t k) {
    const int qk = 32;
    for (int64_t i = 0; i < k / qk; i++) {
        const float d = GGML_FP16_TO_FP32(x[i].d);
        for (int j = 0; j < qk; j++) y[i*qk + j] = x[i].qs[j] * d;
    }
}

typedef void (*dequant_fn)(const void *, float *, int64_t);

#define WRAP(fn, T) static void w_##fn(const void * p, float * y, int64_t k) { fn((const T *) p, y, k); }
WRAP(dequantize_row_q4_0, block_q4_0)
WRAP(dequantize_row_q4_1, block_q4_1)
WRAP(dequantize_row_q5_0, block_q5_0)
WRAP(dequantize_row_q5_1, block_q5_1)
WRAP(dequantize_row_q8_0, block_q8_0)
WRAP(dequantize_row_q8_1_local, block_q8_1)
WRAP(dequantize_row_q2_K, block_q2_K)
WRAP(dequantize_row_q3_K, block_q3_K)
WRAP(dequantize_row_q4_K, block_q4_K)
WRAP(dequantize_row_q5_K, block_q5_K)
WRAP(dequantize_row_q6_K, block_q6_K)
WRAP(dequantize_row_q8_K, block_q8_K)

typedef struct { const char * name; int epb; int bb; dequant_fn fn; } entry;
static const entry table[] = {
    {"f32",    1,   4, dequantize_row_f32_local},
    {"f16",    1,   2, dequantize_row_f16_local},
    {"bf16",   1,   2, dequantize_row_bf16_local},
    {"q4_0",  32,  18, w_dequantize_row_q4_0},
    {"q4_1",  32,  20, w_dequantize_row_q4_1},
    {"q5_0",  32,  22, w_dequantize_row_q5_0},
    {"q5_1",  32,  24, w_dequantize_row_q5_1},
    {"q8_0",  32,  34, w_dequantize_row_q8_0},
    {"q8_1",  32,  36, w_dequantize_row_q8_1_local},
    {"q2_k", 256,  84, w_dequantize_row_q2_K},
    {"q3_k", 256, 110, w_dequantize_row_q3_K},
    {"q4_k", 256, 144, w_dequantize_row_q4_K},
    {"q5_k", 256, 176, w_dequantize_row_q5_K},
    {"q6_k", 256, 210, w_dequantize_row_q6_K},
    {"q8_k", 256, 292, w_dequantize_row_q8_K},
};

static uint8_t * read_file(const char * path, size_t * len) {
    FILE * f = fopen(path, "rb");
    if (!f) { perror(path); exit(2); }
    fseek(f, 0, SEEK_END);
    *len = (size_t) ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t * buf = malloc(*len ? *len : 1);
    if (fread(buf, 1, *len, f) != *len) { fprintf(stderr, "short read\n"); exit(2); }
    fclose(f);
    return buf;
}

int main(int argc, char ** argv) {
    if (argc != 4) { fprintf(stderr, "usage: harness <type> <in.bin> <out.f32>\n"); return 2; }
    const entry * e = NULL;
    for (size_t i = 0; i < sizeof(table)/sizeof(table[0]); i++) {
        if (strcmp(table[i].name, argv[1]) == 0) e = &table[i];
    }
    if (!e) { fprintf(stderr, "unknown type %s\n", argv[1]); return 2; }

    size_t len = 0;
    uint8_t * buf = read_file(argv[2], &len);
    const int64_t n = (int64_t)(len / (size_t) e->bb) * e->epb;
    float * out = malloc(sizeof(float) * (size_t) n);
    e->fn(buf, out, n);

    FILE * f = fopen(argv[3], "wb");
    if (!f) { perror(argv[3]); return 2; }
    fwrite(out, sizeof(float), (size_t) n, f);
    fclose(f);
    printf("%s: %lld elements\n", argv[1], (long long) n);
    free(out);
    free(buf);
    return 0;
}
EOF

clang -O0 -std=c11 -o "$work/harness" "$work/harness.c" -lm

fail=0
for bin in "$root"/tests/fixtures/dequant/*.bin; do
    name="$(basename "$bin" .bin)"
    expect="$root/tests/fixtures/dequant/$name.f32"
    got="$work/$name.f32.c"
    "$work/harness" "$name" "$bin" "$got" > /dev/null
    if cmp -s "$expect" "$got"; then
        echo "  ok   $name (C reference matches committed expectation bit-for-bit)"
    else
        echo "  FAIL $name (C reference differs from $expect)"
        fail=1
    fi
done

if [ "$fail" -ne 0 ]; then
    echo "cross-check FAILED" >&2
    exit 1
fi
echo "all dequant fixtures verified against the compiled ggml reference"
