// ANEDVD — Apple Neural Engine Decoupled Vandal Driver.
//
// CoreML-free LLM inference on the Apple Neural Engine, in Zig. The ANE is
// driven through Apple's private AppleNeuralEngine.framework (_ANEInMemoryModel
// / _ANERequest), with MIL programs generated by this project. No CoreML
// anywhere.

const std = @import("std");
const sys = @import("sys.zig");
const ane = @import("ane/runtime.zig");
const mil = @import("ane/mil.zig");
const weights = @import("ane/weights.zig");

const USAGE =
    \\anedvd — Apple Neural Engine Decoupled Vandal Driver
    \\CoreML-free LLM inference on the Apple Neural Engine, in Zig.
    \\
    \\usage:
    \\  anedvd info                     show ANE availability and device info
    \\  anedvd probe [--size N]         compile+run an ANE matmul and check it vs CPU
    \\  anedvd bench [--size N] [--iters K]
    \\                                  measure ANE matmul throughput
    \\  anedvd selftest [--fuse]        ANE engine vs CPU reference on a tiny model
    \\  anedvd check <model.gguf>       load a real GGUF, compile all ANE kernels, run a step
    \\  anedvd run --model <m.gguf> --prompt "..." [--max-tokens N] [--temp T] [--top-k K]
    \\                                  generate text on the ANE
    \\  anedvd cpu --model <m.gguf> --prompt "..." [--rope-hf] [--chat]
    \\                                  pure-CPU reference (no ANE): sanity-check a model
    \\  anedvd serve --model <m.gguf> [--host 127.0.0.1] [--port 8080] [--name ID]
    \\                                  HTTP server: OpenAI + Anthropic compatible API
    \\                                  and a built-in WebUI at /
    \\
    \\model flags: --rope-hf | --rope-adjacent   force the RoPE convention
    \\             --fuse                         experimental fused FFN (known wrong)
    \\
;

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const argv = try init.minimal.args.toSlice(allocator);
    defer allocator.free(argv);

    if (argv.len < 2) {
        sys.print("{s}", .{USAGE});
        return;
    }
    const cmd = argv[1];

    if (std.mem.eql(u8, cmd, "info")) {
        return cmdInfo();
    } else if (std.mem.eql(u8, cmd, "probe")) {
        return cmdProbe(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "bench")) {
        return cmdBench(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "selftest")) {
        var fuse = false;
        for (argv) |a| if (std.mem.eql(u8, a, "--fuse")) {
            fuse = true;
        };
        return cmdSelftestOpt(allocator, fuse);
    } else if (std.mem.eql(u8, cmd, "check")) {
        return cmdCheck(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "run")) {
        return cmdRun(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "cpu")) {
        return cmdCpu(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "serve")) {
        return cmdServe(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "-h") or std.mem.eql(u8, cmd, "--help")) {
        sys.print("{s}", .{USAGE});
        return;
    }
    sys.eprint("unknown command: {s}\n{s}", .{ cmd, USAGE });
    std.process.exit(2);
}

fn argValue(argv: []const [:0]const u8, name: []const u8, default: u32) u32 {
    for (argv, 0..) |a, i| {
        if (std.mem.eql(u8, a, name) and i + 1 < argv.len) {
            return std.fmt.parseInt(u32, argv[i + 1], 10) catch default;
        }
    }
    return default;
}

fn cmdInfo() !void {
    sys.print("ANEDVD — Apple Neural Engine Decoupled Vandal Driver\n", .{});
    sys.print("CoreML-free ANE runtime, in Zig\n", .{});
    sys.print("zig {s}\n", .{@import("builtin").zig_version_string});

    if (!ane.available()) {
        sys.print("ANE: UNAVAILABLE\n  reason: {s}\n", .{ane.lastError()});
        return;
    }
    sys.print("ANE: available (private AppleNeuralEngine.framework loaded)\n", .{});
    sys.print("  path: /System/Library/PrivateFrameworks/AppleNeuralEngine.framework\n", .{});
    sys.print("  classes: _ANEInMemoryModelDescriptor, _ANEInMemoryModel, _ANERequest, _ANEIOSurfaceObject\n", .{});
    sys.print("  CoreML used: no\n", .{});
    sys.print("  compiles this process: {d}\n", .{ane.compileCount()});
}

/// Deterministic pseudo-random fill so probe results are reproducible.
fn fillLcg(dst: []f32, seed: u32) void {
    var s: u32 = seed;
    for (dst) |*v| {
        s = s *% 1664525 +% 1013904223;
        // map to roughly [-0.5, 0.5)
        const f: f32 = @as(f32, @floatFromInt(s >> 8)) / 16777216.0;
        v.* = f - 0.5;
    }
}

const ProbeResult = struct {
    max_err: f32,
    rel_err: f32,
    eval_us: f64,
};

/// Compile a 1x1 conv (matmul) kernel for [cin] -> [cout] and check it against
/// a CPU reference. Returns the error metrics.
fn runMatmulProbe(allocator: std.mem.Allocator, cin: u32, cout: u32, iters: u32) !ProbeResult {
    const w32 = try allocator.alloc(f32, @as(usize, cout) * cin);
    defer allocator.free(w32);
    const x32 = try allocator.alloc(f32, cin);
    defer allocator.free(x32);
    fillLcg(w32, 12345);
    fillLcg(x32, 777);

    const w16 = try weights.f32ToF16(allocator, w32);
    defer allocator.free(w16);
    const x16 = try weights.f32ToF16(allocator, x32);
    defer allocator.free(x16);

    var sym_buf: [64]u8 = undefined;
    const sym = try weights.symbol(&sym_buf);

    const program = try mil.build(allocator, .{
        .inputs = &.{.{ .name = "i0", .channels = cin }},
        .ops = &.{.{ .conv = .{
            .x = "i0",
            .w = "w0",
            .y = "o0",
            .cin = cin,
            .cout = cout,
            .blob_offset = 64,
            .file = sym,
        } }},
        .outputs = &.{"o0"},
    });
    defer allocator.free(program);

    var kernel = try ane.Kernel.create(allocator, program, &.{.{
        .name = sym,
        .chunks = &.{std.mem.sliceAsBytes(w16)},
    }});
    defer kernel.deinit();
    kernel.zeroInputs();

    try kernel.writeInputF16(0, x16);
    try kernel.eval();
    const y16 = try allocator.alloc(f16, cout);
    defer allocator.free(y16);
    try kernel.readOutputF16(0, y16);

    // CPU reference in f32.
    var max_err: f32 = 0;
    var max_mag: f32 = 0;
    for (0..cout) |o| {
        var acc: f32 = 0;
        for (0..cin) |c| acc += w32[o * cin + c] * x32[c];
        const got: f32 = @floatCast(y16[o]);
        const e = @abs(got - acc);
        if (e > max_err) max_err = e;
        if (@abs(acc) > max_mag) max_mag = @abs(acc);
    }

    // Timing.
    var i: u32 = 0;
    while (i < 5) : (i += 1) try kernel.eval();
    const t0 = sys.nowNs();
    i = 0;
    while (i < iters) : (i += 1) try kernel.eval();
    const t1 = sys.nowNs();
    const eval_us = @as(f64, @floatFromInt(t1 - t0)) / 1000.0 / @as(f64, @floatFromInt(iters));

    return .{
        .max_err = max_err,
        .rel_err = if (max_mag > 0) max_err / max_mag else max_err,
        .eval_us = eval_us,
    };
}

fn cmdProbe(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const size = argValue(argv, "--size", 256);
    sys.print("ANE probe: 1x1 conv (matmul) {d} -> {d}, fp16\n", .{ size, size });

    const r = runMatmulProbe(allocator, size, size, 20) catch |e| {
        sys.print("FAILED: {s}\n", .{@errorName(e)});
        sys.print("  shim error: {s}\n", .{ane.lastError()});
        return;
    };
    sys.print("  max|err| = {e:.6}  rel = {e:.6}\n", .{ r.max_err, r.rel_err });
    sys.print("  eval = {d:.2} us  ({d:.1} GFLOP/s)\n", .{
        r.eval_us,
        2.0 * @as(f64, @floatFromInt(size)) * @as(f64, @floatFromInt(size)) / 1e9 / (r.eval_us / 1e6),
    });
    if (r.rel_err < 0.02) {
        sys.print("  RESULT: CORRECT (ANE output matches CPU reference)\n", .{});
    } else {
        sys.print("  RESULT: MISMATCH\n", .{});
        std.process.exit(1);
    }
}

fn cmdBench(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const iters = argValue(argv, "--iters", 100);
    const sizes = [_]u32{ 128, 256, 512, 1024, 2048, 4096 };
    sys.print("ANE matmul throughput (1x1 conv, fp16, batch 1)\n", .{});
    sys.print("{s:>6} {s:>12} {s:>12}\n", .{ "size", "us/eval", "GFLOP/s" });
    for (sizes) |s| {
        const r = runMatmulProbe(allocator, s, s, iters) catch |e| {
            sys.print("{d:>6} FAILED: {s} ({s})\n", .{ s, @errorName(e), ane.lastError() });
            continue;
        };
        const gflops = 2.0 * @as(f64, @floatFromInt(s)) * @as(f64, @floatFromInt(s)) / 1e9 / (r.eval_us / 1e6);
        sys.print("{d:>6} {d:>12.2} {d:>12.1}\n", .{ s, r.eval_us, gflops });
    }
}

// ---------------------------------------------------------------------------
// selftest: build a tiny random transformer, run it through the ANE engine and
// compare against a pure-CPU reference implementation of the same model.
// ---------------------------------------------------------------------------

const cpu = @import("cpu.zig");
const model_mod = @import("model.zig");
const engine_mod = @import("engine.zig");

fn matmulF16(out: []f32, w: []const f16, x: []const f32, out_dim: usize, in_dim: usize) void {
    for (0..out_dim) |o| {
        var acc: f32 = 0;
        for (0..in_dim) |i| acc += @as(f32, @floatCast(w[o * in_dim + i])) * x[i];
        out[o] = acc;
    }
}

const RefState = struct {
    k: [][]f32,
    v: [][]f32,
};

/// Pure-CPU reference forward, mirroring engine.forward exactly.
fn refForward(
    allocator: std.mem.Allocator,
    mw: *const model_mod.ModelWeights,
    st: *RefState,
    token: u32,
    pos: u32,
) ![]f32 {
    const cfg = mw.config;
    const hidden: usize = cfg.hidden;
    const q_dim: usize = cfg.qDim();
    const kv_dim: usize = cfg.kvDim();
    const inter: usize = cfg.inter;
    const hd: usize = cfg.head_dim;

    const x = try allocator.alloc(f32, hidden);
    defer allocator.free(x);
    const h = try allocator.alloc(f32, hidden);
    defer allocator.free(h);
    const qkv = try allocator.alloc(f32, cfg.qkvDim());
    defer allocator.free(qkv);
    const attn = try allocator.alloc(f32, q_dim);
    defer allocator.free(attn);
    const proj = try allocator.alloc(f32, hidden);
    defer allocator.free(proj);
    const gate = try allocator.alloc(f32, inter);
    defer allocator.free(gate);
    const up = try allocator.alloc(f32, inter);
    defer allocator.free(up);
    const act = try allocator.alloc(f32, inter);
    defer allocator.free(act);
    const scores = try allocator.alloc(f32, pos + 1);
    defer allocator.free(scores);

    for (0..hidden) |i| x[i] = @floatCast(mw.embed[@as(usize, token) * hidden + i]);

    for (mw.layers, 0..) |*lw, li| {
        cpu.rmsnorm(h, x, lw.attn_norm, cfg.eps);
        matmulF16(qkv, lw.qkv, h, cfg.qkvDim(), hidden);
        if (lw.qkv_bias) |b| cpu.addInPlace(qkv, b);
        const q = qkv[0..q_dim];
        const kk = qkv[q_dim..][0..kv_dim];
        const vv = qkv[q_dim + kv_dim ..][0..kv_dim];
        if (cfg.rope_adjacent) {
            cpu.ropeAdjacent(q, cfg.heads, cfg.head_dim, pos, cfg.rope_theta);
            cpu.ropeAdjacent(kk, cfg.kv_heads, cfg.head_dim, pos, cfg.rope_theta);
        } else {
            cpu.rope(q, cfg.heads, cfg.head_dim, pos, cfg.rope_theta);
            cpu.rope(kk, cfg.kv_heads, cfg.head_dim, pos, cfg.rope_theta);
        }
        @memcpy(st.k[li][@as(usize, pos) * kv_dim ..][0..kv_dim], kk);
        @memcpy(st.v[li][@as(usize, pos) * kv_dim ..][0..kv_dim], vv);
        cpu.attentionDecode(attn, q, st.k[li], st.v[li], pos + 1, cfg.heads, cfg.kv_heads, cfg.head_dim, scores);
        matmulF16(proj, lw.o, attn, hidden, q_dim);
        if (lw.o_bias) |b| cpu.addInPlace(proj, b);
        cpu.addInPlace(x, proj);

        cpu.rmsnorm(h, x, lw.ffn_norm, cfg.eps);
        matmulF16(gate, lw.gate, h, inter, hidden);
        matmulF16(up, lw.up, h, inter, hidden);
        cpu.siluMul(act, gate, up);
        matmulF16(proj, lw.down, act, hidden, inter);
        cpu.addInPlace(x, proj);
    }
    _ = hd;
    cpu.rmsnorm(h, x, mw.final_norm, cfg.eps);
    const logits = try allocator.alloc(f32, cfg.vocab);
    matmulF16(logits, mw.headWeights(), h, cfg.vocab, hidden);
    return logits;
}

fn cmdSelftest(allocator: std.mem.Allocator) !void {
    return cmdSelftestOpt(allocator, false);
}

fn cmdSelftestOpt(allocator: std.mem.Allocator, fuse: bool) !void {
    sys.print("selftest: tiny random transformer, ANE engine vs CPU reference (fuse_ffn={})\n", .{fuse});

    const cfg = model_mod.Config{
        .arch = "llama",
        .hidden = 64,
        .layers = 2,
        .heads = 4,
        .kv_heads = 2,
        .head_dim = 16,
        .inter = 128,
        .vocab = 256,
        .eps = 1e-5,
        .rope_theta = 10000.0,
        .tie_embeddings = false,
    };

    var mw: model_mod.ModelWeights = .{ .allocator = allocator, .config = cfg };
    defer mw.deinit();
    mw.embed = try allocator.alloc(f16, @as(usize, cfg.vocab) * cfg.hidden);
    mw.final_norm = try allocator.alloc(f32, cfg.hidden);
    mw.layers = try allocator.alloc(model_mod.LayerWeights, cfg.layers);
    @memset(mw.layers, .{}); // required: optional bias fields must start as null

    var seed: u32 = 99;
    const tmp = try allocator.alloc(f32, @as(usize, cfg.vocab) * cfg.hidden);
    defer allocator.free(tmp);
    fillLcg(tmp, seed);
    for (tmp, 0..) |v, i| mw.embed[i] = @floatCast(v * 0.5);
    for (mw.final_norm) |*v| {
        seed +%= 1;
        fillLcg(tmp[0..1], seed);
        v.* = 0.5 + tmp[0];
    }
    for (mw.layers, 0..) |*lw, li| {
        const qkv_n = @as(usize, cfg.qkvDim()) * cfg.hidden;
        const o_n = @as(usize, cfg.hidden) * cfg.qDim();
        const g_n = @as(usize, cfg.inter) * cfg.hidden;
        const d_n = @as(usize, cfg.hidden) * cfg.inter;
        lw.qkv = try allocator.alloc(f16, qkv_n);
        lw.o = try allocator.alloc(f16, o_n);
        lw.gate = try allocator.alloc(f16, g_n);
        lw.up = try allocator.alloc(f16, g_n);
        lw.down = try allocator.alloc(f16, d_n);
        lw.attn_norm = try allocator.alloc(f32, cfg.hidden);
        lw.ffn_norm = try allocator.alloc(f32, cfg.hidden);

        const scale: f32 = 0.08 / @sqrt(@as(f32, @floatFromInt(cfg.hidden)));
        fillLcg(tmp[0..qkv_n], 1000 + @as(u32, @intCast(li)));
        for (tmp[0..qkv_n], 0..) |v, i| lw.qkv[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..o_n], 2000 + @as(u32, @intCast(li)));
        for (tmp[0..o_n], 0..) |v, i| lw.o[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..g_n], 3000 + @as(u32, @intCast(li)));
        for (tmp[0..g_n], 0..) |v, i| lw.gate[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..g_n], 4000 + @as(u32, @intCast(li)));
        for (tmp[0..g_n], 0..) |v, i| lw.up[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..d_n], 5000 + @as(u32, @intCast(li)));
        for (tmp[0..d_n], 0..) |v, i| lw.down[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..cfg.hidden], 6000 + @as(u32, @intCast(li)));
        for (tmp[0..cfg.hidden], 0..) |v, i| lw.attn_norm[i] = 0.8 + v * 0.4;
        fillLcg(tmp[0..cfg.hidden], 7000 + @as(u32, @intCast(li)));
        for (tmp[0..cfg.hidden], 0..) |v, i| lw.ffn_norm[i] = 0.8 + v * 0.4;
    }

    // The CPU reference keeps its own copy; the engine takes ownership of `mw`.
    var ref_mw = try mw.clone(allocator);
    defer ref_mw.deinit();
    const rt = try mw.toRuntime(allocator);
    var engine = try engine_mod.Engine.init(allocator, rt, mw.layerSource(), mw.headSource(rt.embed), .{
        .max_seq = 64,
        .verbose = true,
        .fuse_ffn = fuse,
    });
    defer engine.deinit();

    var st = RefState{
        .k = try allocator.alloc([]f32, cfg.layers),
        .v = try allocator.alloc([]f32, cfg.layers),
    };
    defer {
        for (st.k) |c| allocator.free(c);
        for (st.v) |c| allocator.free(c);
        allocator.free(st.k);
        allocator.free(st.v);
    }
    for (0..cfg.layers) |i| {
        st.k[i] = try allocator.alloc(f32, 64 * cfg.kvDim());
        st.v[i] = try allocator.alloc(f32, 64 * cfg.kvDim());
        @memset(st.k[i], 0);
        @memset(st.v[i], 0);
    }

    const tokens = [_]u32{ 1, 42, 7, 200, 13 };
    var max_abs: f32 = 0;
    var max_ref: f32 = 0;
    for (tokens, 0..) |tok, pos| {
        const got = try engine.forward(tok, @intCast(pos));
        const ref = try refForward(allocator, &ref_mw, &st, tok, @intCast(pos));
        defer allocator.free(ref);
        var step_max: f32 = 0;
        for (got, ref) |a, b| {
            const d = @abs(a - b);
            if (d > step_max) step_max = d;
            if (d > max_abs) max_abs = d;
            if (@abs(b) > max_ref) max_ref = @abs(b);
        }
        sys.print("  token {d} (id {d}): max|ANE - CPU| = {e:.5}\n", .{ pos, tok, step_max });
    }
    const rel = if (max_ref > 0) max_abs / max_ref else max_abs;
    sys.print("\n  overall max|diff| = {e:.5}  (max|logit| = {e:.4})\n", .{ max_abs, max_ref });
    sys.print("  relative error = {e:.5}  -> {s}\n", .{ rel, if (rel < 0.05) "PASS (ANE path matches the CPU reference)" else "FAIL" });
    sys.print("  ANE evals = {d}, ANE time = {d:.1} ms, {d:.2} tok/s\n", .{
        engine.stats.ane_evals, engine.stats.aneMs(), engine.stats.tokPerSec(),
    });
    if (rel >= 0.05) std.process.exit(1);
}

// ---------------------------------------------------------------------------
// check: load a real GGUF model, compile every ANE kernel and run one step.
// ---------------------------------------------------------------------------

const gguf = @import("gguf.zig");
const load_gguf = @import("load_gguf.zig");

fn cmdCheck(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    if (argv.len < 3) {
        sys.eprint("usage: anedvd check <model.gguf>\n", .{});
        std.process.exit(2);
    }
    const path = argv[2];
    sys.print("loading {s}\n", .{path});
    var g = try gguf.Gguf.load(allocator, path);
    defer g.deinit();
    const cfg = try load_gguf.loadConfig(&g);
    sys.print("  arch={s} hidden={d} layers={d} heads={d}/{d} head_dim={d} inter={d} vocab={d} eps={e} rope_theta={d}\n", .{
        cfg.arch, cfg.hidden, cfg.layers, cfg.heads, cfg.kv_heads, cfg.head_dim, cfg.inter, cfg.vocab, cfg.eps, cfg.rope_theta,
    });
    sys.print("  tensors in file: {d}\n", .{g.tensorCount()});
    const probe_names = [_][]const u8{ "token_embd.weight", "output_norm.weight", "output.weight", "blk.0.attn_norm.weight", "blk.0.attn_q.weight", "blk.0.attn_k.weight", "blk.0.attn_v.weight", "blk.0.attn_output.weight", "blk.0.ffn_gate.weight", "blk.0.ffn_up.weight", "blk.0.ffn_down.weight" };
    for (probe_names) |pn| {
        if (g.tensor(pn)) |t| {
            sys.print("    {s}: dims=", .{pn});
            for (t.dims, 0..) |d, di| {
                if (di > 0) sys.print("x", .{});
                sys.print("{d}", .{d});
            }
            sys.print("  type={s}\n", .{t.ttype.name()});
        } else {
            sys.print("    {s}: MISSING\n", .{pn});
        }
    }

    const rt = try load_gguf.loadRuntime(allocator, &g, cfg, true);
    sys.print("  ANE compiles so far: {d}\n", .{ane.compileCount()});

    const t_c0 = sys.nowNs();
    var fuse = false;
    for (argv) |a| if (std.mem.eql(u8, a, "--fuse")) {
        fuse = true;
    };
    var layers_src = load_gguf.GgufLayers{ .g = &g, .cfg = rt.config };
    var head_src = load_gguf.GgufHead{ .g = &g, .cfg = rt.config, .embed = rt.embed };
    var eng = try engine_mod.Engine.init(allocator, rt, layers_src.source(), head_src.source(), .{
        .max_seq = 512,
        .verbose = true,
        .fuse_ffn = fuse,
    });
    defer eng.deinit();
    const t_c1 = sys.nowNs();
    sys.print("  all kernels compiled in {d:.2} s (ANE compiles: {d})\n", .{ @as(f64, @floatFromInt(t_c1 - t_c0)) / 1e9, ane.compileCount() });
    const ph = ane.phaseMs();
    sys.print("  phase split: write {d:.2} s, ANECCompile {d:.2} s, load {d:.2} s\n", .{ ph.write / 1000.0, ph.compile / 1000.0, ph.load / 1000.0 });

    const logits = try eng.forward(1, 0);
    var max: f32 = -std.math.inf(f32);
    var min: f32 = std.math.inf(f32);
    var nan: usize = 0;
    for (logits) |v| {
        if (std.math.isNan(v)) nan += 1;
        if (v > max) max = v;
        if (v < min) min = v;
    }
    sys.print("  one decode step: logits[{d}] min={e:.4} max={e:.4} nan={d}\n", .{ logits.len, min, max, nan });
    sys.print("  ANE evals={d} ANE time={d:.2} ms\n", .{ eng.stats.ane_evals, eng.stats.aneMs() });
    if (nan > 0) {
        sys.print("  RESULT: FAIL (NaN in logits)\n", .{});
        std.process.exit(1);
    }
    sys.print("  per-kernel check (layer 0, token 1):\n", .{});
    var m0 = try load_gguf.loadLayer(allocator, &g, cfg, 0);
    defer m0.deinit(allocator);
    try eng.diagnose(1, &m0);
    try predictNextTokens(allocator, &g, &eng, "The capital of France is", null);
    try predictNextTokens(allocator, &g, &eng, "2 + 2 =", null);
    sys.print("  RESULT: OK\n", .{});
}

/// Map a plain-text prompt onto vocabulary tokens by exact string match (good
/// enough for a sanity check without a BPE tokenizer) and print the model's
/// top-5 next-token predictions.
fn predictNextTokens(allocator: std.mem.Allocator, g: *const gguf.Gguf, eng: *engine_mod.Engine, prompt: []const u8, mw: ?*const model_mod.ModelWeights) !void {
    const toks = g.getStringArray("tokenizer.ggml.tokens") orelse {
        sys.print("  (no tokenizer.ggml.tokens metadata; skipping prediction)\n", .{});
        return;
    };
    eng.reset();
    var ids = std.ArrayList(u32).empty;
    defer ids.deinit(allocator);

    var it = std.mem.tokenizeAny(u8, prompt, " ");
    var first = true;
    while (it.next()) |word| {
        var found: ?u32 = null;
        // GGUF vocabularies spell a leading space as 'Ġ' (GPT-2 style) or
        // '▁' (SentencePiece); some files keep the plain ASCII space.
        var buf: [128]u8 = undefined;
        var variants: [4][]const u8 = undefined;
        var nvar: usize = 0;
        if (!first) {
            variants[nvar] = std.fmt.bufPrint(&buf, "\u{0120}{s}", .{word}) catch word;
            nvar += 1;
        }
        {
            var buf2: [128]u8 = undefined;
            variants[nvar] = std.fmt.bufPrint(&buf2, "\u{2581}{s}", .{word}) catch word;
            nvar += 1;
            // note: buf2 is a local; copy through a static-safe path below
            variants[nvar - 1] = std.fmt.bufPrint(&buf, "\u{2581}{s}", .{word}) catch word;
        }
        variants[nvar] = word;
        nvar += 1;
        for (variants[0..nvar]) |v| {
            for (toks, 0..) |t, i| {
                if (std.mem.eql(u8, t, v)) {
                    found = @intCast(i);
                    break;
                }
            }
            if (found != null) break;
        }
        if (found) |id| {
            try ids.append(allocator, id);
            sys.print("    token \"{s}\" -> id {d} (\"{s}\")\n", .{ word, id, if (id < toks.len) toks[id] else "?" });
        } else sys.print("  (word \"{s}\" not in vocab)\n", .{word});
        first = false;
    }
    if (ids.items.len == 0) return;

    var logits: []f32 = undefined;
    var ref_st: ?RefState = null;
    defer if (ref_st) |*st| {
        for (st.k) |c| allocator.free(c);
        for (st.v) |c| allocator.free(c);
        allocator.free(st.k);
        allocator.free(st.v);
    };
    if (mw) |m| {
        const L: usize = m.config.layers;
        var st = RefState{ .k = try allocator.alloc([]f32, L), .v = try allocator.alloc([]f32, L) };
        for (0..L) |i| {
            st.k[i] = try allocator.alloc(f32, 2048 * m.config.kvDim());
            st.v[i] = try allocator.alloc(f32, 2048 * m.config.kvDim());
            @memset(st.k[i], 0);
            @memset(st.v[i], 0);
        }
        ref_st = st;
        for (ids.items, 0..) |id, pos| {
            if (pos > 0) allocator.free(logits);
            logits = try refForward(allocator, m, &ref_st.?, id, @intCast(pos));
        }
    } else {
        for (ids.items, 0..) |id, pos| logits = try eng.forward(id, @intCast(pos));
    }

    sys.print("  prompt \"{s}\" ({d} tokens) -> top-5:\n", .{ prompt, ids.items.len });
    var shown: usize = 0;
    var used = try allocator.alloc(bool, logits.len);
    defer allocator.free(used);
    @memset(used, false);
    while (shown < 5) : (shown += 1) {
        var best: usize = 0;
        var best_v: f32 = -std.math.inf(f32);
        for (logits, 0..) |v, i| {
            if (!used[i] and v > best_v) {
                best_v = v;
                best = i;
            }
        }
        used[best] = true;
        const txt = if (best < toks.len) toks[best] else "?";
        sys.print("    {d}. id={d} logit={d:.2} {s}\n", .{ shown + 1, best, best_v, txt });
    }
}

// ---------------------------------------------------------------------------
// run: generate text with a real GGUF model on the ANE.
// ---------------------------------------------------------------------------

const tokenizer_mod = @import("tokenizer.zig");

fn argStr(argv: []const [:0]const u8, name: []const u8) ?[]const u8 {
    for (argv, 0..) |a, i| {
        if (std.mem.eql(u8, a, name) and i + 1 < argv.len) return argv[i + 1];
    }
    return null;
}

fn argF32(argv: []const [:0]const u8, name: []const u8, default: f32) f32 {
    const v = argStr(argv, name) orelse return default;
    return std.fmt.parseFloat(f32, v) catch default;
}

fn cmdRun(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const model_path = argStr(argv, "--model") orelse {
        sys.eprint("usage: anedvd run --model <model.gguf> --prompt \"...\" [--max-tokens N] [--temp T] [--top-k K]\n", .{});
        std.process.exit(2);
    };
    const prompt = argStr(argv, "--prompt") orelse "The capital of France is";
    const max_tokens: u32 = argValue(argv, "--max-tokens", 48);
    const temperature = argF32(argv, "--temp", 0.0);
    const top_k: usize = argValue(argv, "--top-k", 40);
    var fuse = false;
    var rope_hf = false;
    var rope_adj = false;
    for (argv) |a| {
        if (std.mem.eql(u8, a, "--fuse")) fuse = true;
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
    }

    sys.print("loading {s}\n", .{model_path});
    var g = try gguf.Gguf.load(allocator, model_path);
    defer g.deinit();
    var tok = try tokenizer_mod.Tokenizer.fromGguf(allocator, &g);
    defer tok.deinit();
    const cfg = try load_gguf.loadConfig(&g);
    sys.print("  {s}: {d} layers, hidden {d}, vocab {d}\n", .{ cfg.arch, cfg.layers, cfg.hidden, cfg.vocab });

    const t_rt0 = sys.nowNs();
    var rt = try load_gguf.loadRuntime(allocator, &g, cfg, false);
    const t_rt1 = sys.nowNs();
    if (rope_hf) rt.config.rope_adjacent = false;
    if (rope_adj) rt.config.rope_adjacent = true;
    sys.print("  rope: {s}\n", .{if (rt.config.rope_adjacent) "adjacent pairs (llama.cpp NORM)" else "half-split (llama.cpp NEOX)"});
    if (rt.norms.len > 0 and rt.norms[0].qkv_bias != null) sys.print("  attention biases: present\n", .{});
    var layers_src = load_gguf.GgufLayers{ .g = &g, .cfg = rt.config };
    var head_src = load_gguf.GgufHead{ .g = &g, .cfg = rt.config, .embed = rt.embed };
    const t_c0 = sys.nowNs();
    var eng = try engine_mod.Engine.init(allocator, rt, layers_src.source(), head_src.source(), .{
        .max_seq = 1024,
        .verbose = true,
        .fuse_ffn = fuse,
    });
    defer eng.deinit();
    const t_c1 = sys.nowNs();
    sys.print("  {d} ANE kernels compiled\n", .{ane.compileCount()});
    sys.print("  startup: runtime {d:.2} s + kernels {d:.2} s\n", .{
        @as(f64, @floatFromInt(t_rt1 - t_rt0)) / 1e9,
        @as(f64, @floatFromInt(t_c1 - t_c0)) / 1e9,
    });

    // Prompt formatting: ChatML for instruct models that have the tokens.
    var formatted = std.ArrayList(u8).empty;
    defer formatted.deinit(allocator);
    const im_start = tok.tokenId("<|im_start|>");
    const im_end = tok.tokenId("<|im_end|>");
    if (im_start != null and im_end != null) {
        try formatted.appendSlice(allocator, "<|im_start|>user\n");
        try formatted.appendSlice(allocator, prompt);
        try formatted.appendSlice(allocator, "<|im_end|>\n<|im_start|>assistant\n");
    } else {
        try formatted.appendSlice(allocator, prompt);
    }
    const ids = try tok.encode(allocator, formatted.items, true);
    defer allocator.free(ids);
    sys.print("\nprompt ({d} tokens): {s}\n---\n", .{ ids.len, formatted.items });

    // Prefill.
    const t0 = sys.nowNs();
    var logits: []f32 = undefined;
    for (ids, 0..) |id, pos| logits = try eng.forward(id, @intCast(pos));
    const t_prefill = sys.nowNs();

    // Decode.
    var rng: u32 = 0x12345678;
    const eos = tok.eosId();
    var pos: u32 = @intCast(ids.len);
    var produced: u32 = 0;
    var printed_any = false;
    while (produced < max_tokens and pos < 1000) : (produced += 1) {
        const next = if (temperature <= 0) cpu.argmax(logits) else cpu.sampleTopK(logits, temperature, top_k, &rng);
        if (eos != null and next == eos.?) break;
        const bytes = try tok.tokenBytes(allocator, next);
        defer allocator.free(bytes);
        sys.writeAll(1, bytes);
        printed_any = true;
        logits = try eng.forward(next, pos);
        pos += 1;
    }
    const t_end = sys.nowNs();
    if (!printed_any) sys.print("(no output)", .{});

    const decode_ns = t_end - t_prefill;
    const decode_ms = @as(f64, @floatFromInt(decode_ns)) / 1e6;
    sys.print("\n---\n", .{});
    sys.print("prefill: {d} tokens in {d:.2} s ({d:.1} tok/s)\n", .{
        ids.len,
        @as(f64, @floatFromInt(t_prefill - t0)) / 1e9,
        @as(f64, @floatFromInt(ids.len)) / (@as(f64, @floatFromInt(t_prefill - t0)) / 1e9),
    });
    sys.print("decode: {d} tokens in {d:.2} s ({d:.1} tok/s)\n", .{
        produced,
        decode_ms / 1000.0,
        if (decode_ms > 0) @as(f64, @floatFromInt(produced)) / (decode_ms / 1000.0) else 0,
    });
    const total_wall = t_end - t0;
    sys.print("ANE: {d} evals for {d} tokens ({d:.1} kernels/token), {d:.1} ms total, {d:.2} ms/token\n", .{
        eng.stats.ane_evals,
        eng.stats.tokens,
        if (eng.stats.tokens > 0) @as(f64, @floatFromInt(eng.stats.ane_evals)) / @as(f64, @floatFromInt(eng.stats.tokens)) else 0,
        eng.stats.aneMs(),
        if (eng.stats.tokens > 0) eng.stats.aneMs() / @as(f64, @floatFromInt(eng.stats.tokens)) else 0,
    });
    sys.print("ANE share of wall time: {d:.0}%\n", .{
        if (total_wall > 0) 100.0 * @as(f64, @floatFromInt(eng.stats.ane_eval_ns)) / @as(f64, @floatFromInt(total_wall)) else 0,
    });
}

// ---------------------------------------------------------------------------
// cpu: pure-CPU reference generation, used to validate model handling without
// compiling any ANE kernels.
// ---------------------------------------------------------------------------

fn cmdCpu(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const model_path = argStr(argv, "--model") orelse {
        sys.eprint("usage: anedvd cpu --model <m.gguf> --prompt \"...\" [--rope-hf] [--chat] [--max-tokens N]\n", .{});
        std.process.exit(2);
    };
    const prompt = argStr(argv, "--prompt") orelse "The capital of France is";
    const max_tokens: u32 = argValue(argv, "--max-tokens", 24);
    var rope_hf = false;
    var rope_adj = false;
    var chat = false;
    for (argv) |a| {
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
        if (std.mem.eql(u8, a, "--chat")) chat = true;
    }

    var g = try gguf.Gguf.load(allocator, model_path);
    defer g.deinit();
    var tok = try tokenizer_mod.Tokenizer.fromGguf(allocator, &g);
    defer tok.deinit();
    var mw = try load_gguf.loadWeights(allocator, &g, false);
    defer mw.deinit();
    if (rope_hf) mw.config.rope_adjacent = false;
    if (rope_adj) mw.config.rope_adjacent = true;
    const cfg = mw.config;
    sys.print("cpu reference: {s} hidden={d} layers={d} heads={d}/{d} rope_adjacent={}\n", .{
        cfg.arch, cfg.hidden, cfg.layers, cfg.heads, cfg.kv_heads, cfg.rope_adjacent,
    });

    var text = std.ArrayList(u8).empty;
    defer text.deinit(allocator);
    const has_chatml = tok.tokenId("<|im_start|>") != null and tok.tokenId("<|im_end|>") != null;
    if (chat and has_chatml) {
        try text.appendSlice(allocator, "<|im_start|>user\n");
        try text.appendSlice(allocator, prompt);
        try text.appendSlice(allocator, "<|im_end|>\n<|im_start|>assistant\n");
    } else {
        try text.appendSlice(allocator, prompt);
    }
    const ids = try tok.encode(allocator, text.items, true);
    defer allocator.free(ids);

    const L: usize = cfg.layers;
    var st = RefState{ .k = try allocator.alloc([]f32, L), .v = try allocator.alloc([]f32, L) };
    defer {
        for (st.k) |c| allocator.free(c);
        for (st.v) |c| allocator.free(c);
        allocator.free(st.k);
        allocator.free(st.v);
    }
    for (0..L) |i| {
        st.k[i] = try allocator.alloc(f32, 1024 * cfg.kvDim());
        st.v[i] = try allocator.alloc(f32, 1024 * cfg.kvDim());
        @memset(st.k[i], 0);
        @memset(st.v[i], 0);
    }

    sys.print("prompt ({d} tokens): ", .{ids.len});
    const pbytes = try tok.decode(allocator, ids);
    defer allocator.free(pbytes);
    sys.print("{s}\n---\n", .{pbytes});

    const t0 = sys.nowNs();
    var logits: []f32 = undefined;
    for (ids, 0..) |id, pos| {
        if (pos > 0) allocator.free(logits);
        logits = try refForward(allocator, &mw, &st, id, @intCast(pos));
    }
    defer allocator.free(logits);
    const t1 = sys.nowNs();

    const eos = tok.eosId();
    var produced: u32 = 0;
    var pos: u32 = @intCast(ids.len);
    while (produced < max_tokens) : (produced += 1) {
        const next = cpu.argmax(logits);
        if (eos != null and next == eos.?) break;
        const bytes = try tok.tokenBytes(allocator, next);
        defer allocator.free(bytes);
        sys.writeAll(1, bytes);
        if (pos > 0) allocator.free(logits);
        logits = try refForward(allocator, &mw, &st, next, pos);
        pos += 1;
    }
    const t2 = sys.nowNs();
    sys.print("\n---\ncpu prefill {d:.2} s, decode {d:.2} s ({d:.1} tok/s)\n", .{
        @as(f64, @floatFromInt(t1 - t0)) / 1e9,
        @as(f64, @floatFromInt(t2 - t1)) / 1e9,
        @as(f64, @floatFromInt(produced)) / (@as(f64, @floatFromInt(t2 - t1)) / 1e9),
    });
}

// ---------------------------------------------------------------------------
// serve: OpenAI- and Anthropic-compatible HTTP API plus the built-in WebUI.
// ---------------------------------------------------------------------------

const server_mod = @import("server.zig");
const generate_mod = @import("generate.zig");

fn fileStem(path: []const u8) []const u8 {
    const base = std.fs.path.basename(path);
    const ext = std.fs.path.extension(base);
    return base[0 .. base.len - ext.len];
}

fn cmdServe(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const model_path = argStr(argv, "--model") orelse {
        sys.eprint("usage: anedvd serve --model <model.gguf> [--host 127.0.0.1] [--port 8080] [--name ID] [--system \"...\"]\n", .{});
        std.process.exit(2);
    };
    const host = argStr(argv, "--host") orelse "127.0.0.1";
    const port: u16 = @intCast(argValue(argv, "--port", 8080));
    const model_name = argStr(argv, "--name") orelse fileStem(model_path);
    const system = argStr(argv, "--system");
    const max_seq: u32 = argValue(argv, "--max-seq", 2048);
    const default_max_tokens: u32 = argValue(argv, "--max-tokens", 512);
    var fuse = false;
    var rope_hf = false;
    var rope_adj = false;
    for (argv) |a| {
        if (std.mem.eql(u8, a, "--fuse")) fuse = true;
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
    }

    sys.print("loading {s}\n", .{model_path});
    var g = try gguf.Gguf.load(allocator, model_path);
    defer g.deinit();
    var tok = try tokenizer_mod.Tokenizer.fromGguf(allocator, &g);
    defer tok.deinit();
    const cfg = try load_gguf.loadConfig(&g);
    sys.print("  {s}: {d} layers, hidden {d}, vocab {d}, rope {s}\n", .{
        cfg.arch,                                            cfg.layers, cfg.hidden, cfg.vocab,
        if (cfg.rope_adjacent) "adjacent" else "half-split",
    });

    var rt = try load_gguf.loadRuntime(allocator, &g, cfg, false);
    if (rope_hf) rt.config.rope_adjacent = false;
    if (rope_adj) rt.config.rope_adjacent = true;

    var layers_src = load_gguf.GgufLayers{ .g = &g, .cfg = rt.config };
    var head_src = load_gguf.GgufHead{ .g = &g, .cfg = rt.config, .embed = rt.embed };
    var eng = try engine_mod.Engine.init(allocator, rt, layers_src.source(), head_src.source(), .{
        .max_seq = max_seq,
        .verbose = true,
        .fuse_ffn = fuse,
    });
    defer eng.deinit();
    sys.print("  {d} ANE kernels compiled\n", .{ane.compileCount()});

    var session = generate_mod.Session.init(allocator, &eng, &tok);
    if (tok.eosId()) |eos| {
        const stops = try allocator.alloc(u32, 1);
        stops[0] = eos;
        session.stop_ids = stops;
    }

    var srv = server_mod.Server{
        .allocator = allocator,
        .session = &session,
        .opts = .{
            .host = host,
            .port = port,
            .model_name = model_name,
            .default_system = system,
            .default_max_tokens = default_max_tokens,
        },
    };
    try srv.run();
}
