// ANEDVD — Apple Neural Engine Decoupled Vandal Driver.
//
// CoreML-free LLM inference on the Apple Neural Engine, in Zig. The ANE is
// driven through Apple's private AppleNeuralEngine.framework (_ANEInMemoryModel
// / _ANERequest), with MIL programs generated by this project. No CoreML
// anywhere.

const std = @import("std");
const sys = @import("sys.zig");
const ane = @import("ane/runtime.zig");
const mil = @import("ane/mil.zig");
const weights = @import("ane/weights.zig");

const USAGE =
    \\anedvd — Apple Neural Engine Decoupled Vandal Driver
    \\CoreML-free LLM inference on the Apple Neural Engine, in Zig.
    \\
    \\usage:
    \\  anedvd info                     show ANE availability and device info
    \\  anedvd probe [--size N]         compile+run an ANE matmul and check it vs CPU
    \\  anedvd bench [--size N] [--iters K]
    \\                                  measure ANE matmul throughput
    \\  anedvd width [--size N]         cost of extra activation columns (prefill batching)
    \\  anedvd attnbench [--ctx N]      CPU attention cost breakdown (dot / softmax / AV)
    \\  anedvd kernels <model> [--iters K] [--chunk N]
    \\                                  per-kernel timing and weight-bandwidth of a real model
    \\  anedvd selftest [--split]       ANE engine vs CPU reference on a tiny model
    \\  anedvd check <model.gguf>       load a real GGUF, compile all ANE kernels, run a step
    \\  anedvd run --model <m.gguf> --prompt "..." [--max-tokens N] [--temp T] [--top-k K]
    \\                                  generate text on the ANE
    \\  anedvd cpu --model <m.gguf> --prompt "..." [--rope-hf] [--chat]
    \\                                  pure-CPU reference (no ANE): sanity-check a model
    \\  anedvd chat --model <m.gguf|hf-dir> [--system "..."]
    \\                                  interactive multi-turn chat in the terminal
    \\  anedvd serve --model <m.gguf> [--host 127.0.0.1] [--port 8080] [--name ID]
    \\                                  HTTP server: OpenAI + Anthropic compatible API
    \\                                  and a built-in WebUI at /
    \\
    \\model flags: --rope-hf | --rope-adjacent   force the RoPE convention
    \\             --chunk N                      activation width (default 64; prompt batching)
    \\             --split                        use two kernels for the FFN instead of one
    \\
;

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const argv = try init.minimal.args.toSlice(allocator);
    defer allocator.free(argv);

    if (argv.len < 2) {
        sys.print("{s}", .{USAGE});
        return;
    }
    const cmd = argv[1];

    if (std.mem.eql(u8, cmd, "info")) {
        return cmdInfo();
    } else if (std.mem.eql(u8, cmd, "probe")) {
        return cmdProbe(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "bench")) {
        return cmdBench(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "verify")) {
        return cmdVerify(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "layers")) {
        return cmdLayers(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "kernels")) {
        return cmdKernels(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "attnbench")) {
        return cmdAttnBench(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "width")) {
        return cmdWidthSweep(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "selftest")) {
        var fuse = true;
        for (argv) |a| if (std.mem.eql(u8, a, "--split")) {
            fuse = false;
        };
        return cmdSelftestOpt(allocator, fuse);
    } else if (std.mem.eql(u8, cmd, "check")) {
        return cmdCheck(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "run")) {
        return cmdRun(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "cpu")) {
        return cmdCpu(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "serve")) {
        return cmdServe(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "chat")) {
        return cmdChat(allocator, argv);
    } else if (std.mem.eql(u8, cmd, "-h") or std.mem.eql(u8, cmd, "--help")) {
        sys.print("{s}", .{USAGE});
        return;
    }
    sys.eprint("unknown command: {s}\n{s}", .{ cmd, USAGE });
    std.process.exit(2);
}

fn argValue(argv: []const [:0]const u8, name: []const u8, default: u32) u32 {
    for (argv, 0..) |a, i| {
        if (std.mem.eql(u8, a, name) and i + 1 < argv.len) {
            return std.fmt.parseInt(u32, argv[i + 1], 10) catch default;
        }
    }
    return default;
}

fn cmdInfo() !void {
    sys.print("ANEDVD — Apple Neural Engine Decoupled Vandal Driver\n", .{});
    sys.print("CoreML-free ANE runtime, in Zig\n", .{});
    sys.print("zig {s}\n", .{@import("builtin").zig_version_string});

    if (!ane.available()) {
        sys.print("ANE: UNAVAILABLE\n  reason: {s}\n", .{ane.lastError()});
        return;
    }
    sys.print("ANE: available (private AppleNeuralEngine.framework loaded)\n", .{});
    sys.print("  path: /System/Library/PrivateFrameworks/AppleNeuralEngine.framework\n", .{});
    sys.print("  classes: _ANEInMemoryModelDescriptor, _ANEInMemoryModel, _ANERequest, _ANEIOSurfaceObject\n", .{});
    sys.print("  CoreML used: no\n", .{});
    sys.print("  compiles this process: {d}\n", .{ane.compileCount()});
}

/// Deterministic pseudo-random fill so probe results are reproducible.
fn fillLcg(dst: []f32, seed: u32) void {
    var s: u32 = seed;
    for (dst) |*v| {
        s = s *% 1664525 +% 1013904223;
        // map to roughly [-0.5, 0.5)
        const f: f32 = @as(f32, @floatFromInt(s >> 8)) / 16777216.0;
        v.* = f - 0.5;
    }
}

const ProbeResult = struct {
    max_err: f32,
    rel_err: f32,
    eval_us: f64,
};

/// Compile a 1x1 conv (matmul) kernel for [cin] -> [cout] and check it against
/// a CPU reference. Returns the error metrics.
fn runMatmulProbe(allocator: std.mem.Allocator, cin: u32, cout: u32, iters: u32) !ProbeResult {
    return runMatmulProbeWidth(allocator, cin, cout, iters, 1);
}

fn runMatmulProbeWidth(allocator: std.mem.Allocator, cin: u32, cout: u32, iters: u32, width: u32) !ProbeResult {
    const w32 = try allocator.alloc(f32, @as(usize, cout) * cin);
    defer allocator.free(w32);
    const x32 = try allocator.alloc(f32, @as(usize, cin) * width);
    defer allocator.free(x32);
    fillLcg(w32, 12345);
    fillLcg(x32, 777);

    const w16 = try weights.f32ToF16(allocator, w32);
    defer allocator.free(w16);
    const x16 = try weights.f32ToF16(allocator, x32);
    defer allocator.free(x16);

    var sym_buf: [64]u8 = undefined;
    const sym = try weights.symbol(&sym_buf);

    const program = try mil.build(allocator, .{
        .inputs = &.{.{ .name = "i0", .channels = cin, .width = width }},
        .ops = &.{.{ .conv = .{
            .x = "i0",
            .w = "w0",
            .y = "o0",
            .cin = cin,
            .cout = cout,
            .blob_offset = 64,
            .file = sym,
            .width = width,
        } }},
        .outputs = &.{"o0"},
    });
    defer allocator.free(program);

    var kernel = try ane.Kernel.create(allocator, program, &.{.{
        .name = sym,
        .chunks = &.{std.mem.sliceAsBytes(w16)},
    }});
    defer kernel.deinit();
    kernel.zeroInputs();

    try kernel.writeInputF16(0, x16);
    try kernel.eval();
    const y16 = try allocator.alloc(f16, @as(usize, cout) * width);
    defer allocator.free(y16);
    try kernel.readOutputF16(0, y16);

    // CPU reference in f32.
    var max_err: f32 = 0;
    var max_mag: f32 = 0;
    for (0..cout) |o| {
        for (0..width) |j| {
            var acc: f32 = 0;
            for (0..cin) |c| acc += w32[o * cin + c] * x32[c * width + j];
            const got: f32 = @floatCast(y16[o * width + j]);
            const e = @abs(got - acc);
            if (e > max_err) max_err = e;
            if (@abs(acc) > max_mag) max_mag = @abs(acc);
        }
    }

    // Timing.
    var i: u32 = 0;
    while (i < 5) : (i += 1) try kernel.eval();
    const t0 = sys.nowNs();
    i = 0;
    while (i < iters) : (i += 1) try kernel.eval();
    const t1 = sys.nowNs();
    const eval_us = @as(f64, @floatFromInt(t1 - t0)) / 1000.0 / @as(f64, @floatFromInt(iters));

    return .{
        .max_err = max_err,
        .rel_err = if (max_mag > 0) max_err / max_mag else max_err,
        .eval_us = eval_us,
    };
}

fn cmdProbe(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const size = argValue(argv, "--size", 256);
    sys.print("ANE probe: 1x1 conv (matmul) {d} -> {d}, fp16\n", .{ size, size });

    const r = runMatmulProbe(allocator, size, size, 20) catch |e| {
        sys.print("FAILED: {s}\n", .{@errorName(e)});
        sys.print("  shim error: {s}\n", .{ane.lastError()});
        return;
    };
    sys.print("  max|err| = {e:.6}  rel = {e:.6}\n", .{ r.max_err, r.rel_err });
    sys.print("  eval = {d:.2} us  ({d:.1} GFLOP/s)\n", .{
        r.eval_us,
        2.0 * @as(f64, @floatFromInt(size)) * @as(f64, @floatFromInt(size)) / 1e9 / (r.eval_us / 1e6),
    });
    if (r.rel_err < 0.02) {
        sys.print("  RESULT: CORRECT (ANE output matches CPU reference)\n", .{});
    } else {
        sys.print("  RESULT: MISMATCH\n", .{});
        std.process.exit(1);
    }
}

fn cmdBench(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const iters = argValue(argv, "--iters", 100);
    const sizes = [_]u32{ 128, 256, 512, 1024, 2048, 4096 };
    sys.print("ANE matmul throughput (1x1 conv, fp16, batch 1)\n", .{});
    sys.print("{s:>6} {s:>12} {s:>12}\n", .{ "size", "us/eval", "GFLOP/s" });
    for (sizes) |s| {
        const r = runMatmulProbe(allocator, s, s, iters) catch |e| {
            sys.print("{d:>6} FAILED: {s} ({s})\n", .{ s, @errorName(e), ane.lastError() });
            continue;
        };
        const gflops = 2.0 * @as(f64, @floatFromInt(s)) * @as(f64, @floatFromInt(s)) / 1e9 / (r.eval_us / 1e6);
        sys.print("{d:>6} {d:>12.2} {d:>12.1}\n", .{ s, r.eval_us, gflops });
    }
}

// ---------------------------------------------------------------------------
// selftest: build a tiny random transformer, run it through the ANE engine and
// compare against a pure-CPU reference implementation of the same model.
// ---------------------------------------------------------------------------

const cpu = @import("cpu.zig");
const model_mod = @import("model.zig");
const engine_mod = @import("engine.zig");

fn matmulF16(out: []f32, w: []const f16, x: []const f32, out_dim: usize, in_dim: usize) void {
    for (0..out_dim) |o| {
        var acc: f32 = 0;
        for (0..in_dim) |i| acc += @as(f32, @floatCast(w[o * in_dim + i])) * x[i];
        out[o] = acc;
    }
}

const RefState = struct {
    k: [][]f16,
    v: [][]f16,
};

/// Pure-CPU reference forward, mirroring engine.forward exactly.
fn refForward(
    allocator: std.mem.Allocator,
    mw: *const model_mod.ModelWeights,
    st: *RefState,
    token: u32,
    pos: u32,
    layers: usize,
) ![]f32 {
    const cfg = mw.config;
    const hidden: usize = cfg.hidden;
    const q_dim: usize = cfg.qDim();
    const kv_dim: usize = cfg.kvDim();
    const inter: usize = cfg.inter;
    const hd: usize = cfg.head_dim;

    const x = try allocator.alloc(f32, hidden);
    defer allocator.free(x);
    const h = try allocator.alloc(f32, hidden);
    defer allocator.free(h);
    const qkv = try allocator.alloc(f32, cfg.qkvDim());
    defer allocator.free(qkv);
    const attn = try allocator.alloc(f32, q_dim);
    defer allocator.free(attn);
    const proj = try allocator.alloc(f32, hidden);
    defer allocator.free(proj);
    const gate = try allocator.alloc(f32, inter);
    defer allocator.free(gate);
    const up = try allocator.alloc(f32, inter);
    defer allocator.free(up);
    const act = try allocator.alloc(f32, inter);
    defer allocator.free(act);
    const scores = try allocator.alloc(f32, pos + 1);
    defer allocator.free(scores);

    for (0..hidden) |i| x[i] = @floatCast(mw.embed[@as(usize, token) * hidden + i]);

    for (mw.layers[0..@min(layers, mw.layers.len)], 0..) |*lw, li| {
        cpu.rmsnorm(h, x, lw.attn_norm, cfg.eps);
        matmulF16(qkv, lw.qkv, h, cfg.qkvDim(), hidden);
        if (lw.qkv_bias) |b| cpu.addInPlace(qkv, b);
        const q = qkv[0..q_dim];
        const kk = qkv[q_dim..][0..kv_dim];
        const vv = qkv[q_dim + kv_dim ..][0..kv_dim];
        // Qwen3 normalises each head's q/k before RoPE; the reference has to do
        // the same or `verify` reports a mismatch that is the reference's fault.
        if (lw.q_norm) |w| {
            for (0..cfg.heads) |qh| {
                const v = q[qh * cfg.head_dim ..][0..cfg.head_dim];
                cpu.rmsnorm(v, v, w, cfg.eps);
            }
        }
        if (lw.k_norm) |w| {
            for (0..cfg.kv_heads) |kh| {
                const v = kk[kh * cfg.head_dim ..][0..cfg.head_dim];
                cpu.rmsnorm(v, v, w, cfg.eps);
            }
        }
        if (cfg.rope_adjacent) {
            cpu.ropeAdjacent(q, cfg.heads, cfg.head_dim, pos, cfg.rope_theta);
            cpu.ropeAdjacent(kk, cfg.kv_heads, cfg.head_dim, pos, cfg.rope_theta);
        } else {
            cpu.rope(q, cfg.heads, cfg.head_dim, pos, cfg.rope_theta);
            cpu.rope(kk, cfg.kv_heads, cfg.head_dim, pos, cfg.rope_theta);
        }
        for (0..kv_dim) |i| {
            st.k[li][@as(usize, pos) * kv_dim + i] = @floatCast(kk[i]);
            st.v[li][@as(usize, pos) * kv_dim + i] = @floatCast(vv[i]);
        }
        cpu.attentionDecode(attn, q, st.k[li], st.v[li], pos + 1, cfg.heads, cfg.kv_heads, cfg.head_dim, scores);
        matmulF16(proj, lw.o, attn, hidden, q_dim);
        if (lw.o_bias) |b| cpu.addInPlace(proj, b);
        cpu.addInPlace(x, proj);

        cpu.rmsnorm(h, x, lw.ffn_norm, cfg.eps);
        matmulF16(gate, lw.gate, h, inter, hidden);
        matmulF16(up, lw.up, h, inter, hidden);
        cpu.siluMul(act, gate, up);
        matmulF16(proj, lw.down, act, hidden, inter);
        cpu.addInPlace(x, proj);
    }
    _ = hd;
    cpu.rmsnorm(h, x, mw.final_norm, cfg.eps);
    const logits = try allocator.alloc(f32, cfg.vocab);
    matmulF16(logits, mw.headWeights(), h, cfg.vocab, hidden);
    return logits;
}

fn cmdSelftest(allocator: std.mem.Allocator) !void {
    return cmdSelftestOpt(allocator, true);
}

fn cmdSelftestOpt(allocator: std.mem.Allocator, fuse: bool) !void {
    sys.print("selftest: tiny random transformer, ANE engine vs CPU reference (fuse_ffn={})\n", .{fuse});

    const cfg = model_mod.Config{
        .arch = "llama",
        .hidden = 64,
        .layers = 2,
        .heads = 4,
        .kv_heads = 2,
        .head_dim = 16,
        .inter = 128,
        .vocab = 256,
        .eps = 1e-5,
        .rope_theta = 10000.0,
        .tie_embeddings = false,
    };

    var mw: model_mod.ModelWeights = .{ .allocator = allocator, .config = cfg };
    defer mw.deinit();
    mw.embed = try allocator.alloc(f16, @as(usize, cfg.vocab) * cfg.hidden);
    mw.final_norm = try allocator.alloc(f32, cfg.hidden);
    mw.layers = try allocator.alloc(model_mod.LayerWeights, cfg.layers);
    @memset(mw.layers, .{}); // required: optional bias fields must start as null

    var seed: u32 = 99;
    const tmp = try allocator.alloc(f32, @as(usize, cfg.vocab) * cfg.hidden);
    defer allocator.free(tmp);
    fillLcg(tmp, seed);
    for (tmp, 0..) |v, i| mw.embed[i] = @floatCast(v * 0.5);
    for (mw.final_norm) |*v| {
        seed +%= 1;
        fillLcg(tmp[0..1], seed);
        v.* = 0.5 + tmp[0];
    }
    for (mw.layers, 0..) |*lw, li| {
        const qkv_n = @as(usize, cfg.qkvDim()) * cfg.hidden;
        const o_n = @as(usize, cfg.hidden) * cfg.qDim();
        const g_n = @as(usize, cfg.inter) * cfg.hidden;
        const d_n = @as(usize, cfg.hidden) * cfg.inter;
        lw.qkv = try allocator.alloc(f16, qkv_n);
        lw.o = try allocator.alloc(f16, o_n);
        lw.gate = try allocator.alloc(f16, g_n);
        lw.up = try allocator.alloc(f16, g_n);
        lw.down = try allocator.alloc(f16, d_n);
        lw.attn_norm = try allocator.alloc(f32, cfg.hidden);
        lw.ffn_norm = try allocator.alloc(f32, cfg.hidden);

        const scale: f32 = 0.08 / @sqrt(@as(f32, @floatFromInt(cfg.hidden)));
        fillLcg(tmp[0..qkv_n], 1000 + @as(u32, @intCast(li)));
        for (tmp[0..qkv_n], 0..) |v, i| lw.qkv[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..o_n], 2000 + @as(u32, @intCast(li)));
        for (tmp[0..o_n], 0..) |v, i| lw.o[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..g_n], 3000 + @as(u32, @intCast(li)));
        for (tmp[0..g_n], 0..) |v, i| lw.gate[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..g_n], 4000 + @as(u32, @intCast(li)));
        for (tmp[0..g_n], 0..) |v, i| lw.up[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..d_n], 5000 + @as(u32, @intCast(li)));
        for (tmp[0..d_n], 0..) |v, i| lw.down[i] = @floatCast(v * scale * 8);
        fillLcg(tmp[0..cfg.hidden], 6000 + @as(u32, @intCast(li)));
        for (tmp[0..cfg.hidden], 0..) |v, i| lw.attn_norm[i] = 0.8 + v * 0.4;
        fillLcg(tmp[0..cfg.hidden], 7000 + @as(u32, @intCast(li)));
        for (tmp[0..cfg.hidden], 0..) |v, i| lw.ffn_norm[i] = 0.8 + v * 0.4;
    }

    // The CPU reference keeps its own copy; the engine takes ownership of `mw`.
    var ref_mw = try mw.clone(allocator);
    defer ref_mw.deinit();
    const rt = try mw.toRuntime(allocator);
    var engine = try engine_mod.Engine.init(allocator, rt, mw.layerSource(), mw.headSource(rt.embed), .{
        .max_seq = 64,
        .verbose = true,
        .fuse_ffn = fuse,
    });
    defer engine.deinit();

    var st = RefState{
        .k = try allocator.alloc([]f16, cfg.layers),
        .v = try allocator.alloc([]f16, cfg.layers),
    };
    defer {
        for (st.k) |c| allocator.free(c);
        for (st.v) |c| allocator.free(c);
        allocator.free(st.k);
        allocator.free(st.v);
    }
    for (0..cfg.layers) |i| {
        st.k[i] = try allocator.alloc(f16, 64 * cfg.kvDim());
        st.v[i] = try allocator.alloc(f16, 64 * cfg.kvDim());
        @memset(st.k[i], 0);
        @memset(st.v[i], 0);
    }

    const tokens = [_]u32{ 1, 42, 7, 200, 13 };
    var max_abs: f32 = 0;
    var max_ref: f32 = 0;
    for (tokens, 0..) |tok, pos| {
        const got = try engine.forward(tok, @intCast(pos));
        const ref = try refForward(allocator, &ref_mw, &st, tok, @intCast(pos), cfg.layers);
        defer allocator.free(ref);
        var step_max: f32 = 0;
        for (got, ref) |a, b| {
            const d = @abs(a - b);
            if (d > step_max) step_max = d;
            if (d > max_abs) max_abs = d;
            if (@abs(b) > max_ref) max_ref = @abs(b);
        }
        sys.print("  token {d} (id {d}): max|ANE - CPU| = {e:.5}\n", .{ pos, tok, step_max });
    }
    const rel = if (max_ref > 0) max_abs / max_ref else max_abs;
    sys.print("\n  overall max|diff| = {e:.5}  (max|logit| = {e:.4})\n", .{ max_abs, max_ref });
    sys.print("  relative error = {e:.5}  -> {s}\n", .{ rel, if (rel < 0.05) "PASS (ANE path matches the CPU reference)" else "FAIL" });
    sys.print("  ANE evals = {d}, ANE time = {d:.1} ms, {d:.2} tok/s\n", .{
        engine.stats.ane_evals, engine.stats.aneMs(), engine.stats.tokPerSec(),
    });
    if (rel >= 0.05) std.process.exit(1);
}

// ---------------------------------------------------------------------------
// check: load a real GGUF model, compile every ANE kernel and run one step.
// ---------------------------------------------------------------------------

const gguf = @import("gguf.zig");
const load_gguf = @import("load_gguf.zig");
const load_hf = @import("load_hf.zig");
const hf = @import("hf.zig");

fn cmdCheck(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    if (argv.len < 3) {
        sys.eprint("usage: anedvd check <model.gguf|hf-dir> [--split]\n", .{});
        std.process.exit(2);
    }
    const path = argv[2];
    var fuse = true;
    var rope_hf = false;
    var rope_adj = false;
    var chunk: u32 = 64;
    for (argv, 0..) |a, i| {
        if (std.mem.eql(u8, a, "--split")) fuse = false;
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
        if (std.mem.eql(u8, a, "--chunk") and i + 1 < argv.len) chunk = std.fmt.parseInt(u32, argv[i + 1], 10) catch chunk;
    }

    sys.print("loading {s}\n", .{path});
    var loaded = try model_open.open(allocator, path, .{
        .progress = true,
        .rope_hf = rope_hf,
        .rope_adjacent = rope_adj,
    });
    defer loaded.deinit();
    const cfg = loaded.config;
    sys.print("  {s} ({s}): hidden={d} layers={d} heads={d}/{d} head_dim={d} inter={d} vocab={d} eps={e} rope_theta={d}\n", .{
        cfg.arch,
        if (loaded.format == .gguf) "GGUF" else "safetensors",
        cfg.hidden,
        cfg.layers,
        cfg.heads,
        cfg.kv_heads,
        cfg.head_dim,
        cfg.inter,
        cfg.vocab,
        cfg.eps,
        cfg.rope_theta,
    });
    sys.print("  rope: {s}, attention biases: {s}\n", .{
        if (cfg.rope_adjacent) "adjacent pairs" else "half-split",
        if (loaded.rt.norms.len > 0 and loaded.rt.norms[0].qkv_bias != null) "present" else "none",
    });

    var eng = try engine_mod.Engine.init(allocator, loaded.rt, loaded.layers, loaded.head, .{
        .max_seq = 512,
        .verbose = true,
        .fuse_ffn = fuse,
        .chunk = chunk,
    });
    defer eng.deinit();
    sys.print("  ANE kernels: {d}\n", .{ane.compileCount()});
    const ph = ane.phaseMs();
    sys.print("  phase split: write {d:.2} s, ANECCompile {d:.2} s, load {d:.2} s\n", .{ ph.write / 1000.0, ph.compile / 1000.0, ph.load / 1000.0 });

    const logits = try eng.forward(1, 0);
    var max: f32 = -std.math.inf(f32);
    var min: f32 = std.math.inf(f32);
    var nan: usize = 0;
    for (logits) |v| {
        if (std.math.isNan(v)) nan += 1;
        if (v > max) max = v;
        if (v < min) min = v;
    }
    sys.print("  one decode step: logits[{d}] min={e:.4} max={e:.4} nan={d}\n", .{ logits.len, min, max, nan });
    if (nan > 0) {
        sys.print("  RESULT: FAIL (NaN in logits)\n", .{});
        std.process.exit(1);
    }

    sys.print("  per-kernel check (layer 0, token 1):\n", .{});
    var m0 = try loaded.layers.load(allocator, 0);
    defer m0.deinit(allocator);
    try eng.diagnose(1, &m0);

    try predictNextTokens(allocator, &loaded.tokenizer, &eng, "The capital of France is");
    try predictNextTokens(allocator, &loaded.tokenizer, &eng, "2 + 2 =");
    sys.print("  RESULT: OK\n", .{});
}

/// Prompt the model with plain text and print the top-5 next tokens. Used by
/// `check` as a smoke test; works for either model format via the tokenizer.
fn predictNextTokens(
    allocator: std.mem.Allocator,
    tok: *const tokenizer_mod.Tokenizer,
    eng: *engine_mod.Engine,
    prompt: []const u8,
) !void {
    var ids: std.ArrayList(u32) = .empty;
    defer ids.deinit(allocator);

    var it = std.mem.tokenizeAny(u8, prompt, " ");
    var first = true;
    while (it.next()) |word| {
        var found: ?u32 = null;
        // GGUF vocabularies spell a leading space as 'Ġ' (GPT-2 style) or
        // '▁' (SentencePiece); some files keep the plain ASCII space.
        var buf: [128]u8 = undefined;
        var variants: [3][]const u8 = undefined;
        var nvar: usize = 0;
        if (!first) {
            variants[nvar] = std.fmt.bufPrint(&buf, "\u{0120}{s}", .{word}) catch word;
            nvar += 1;
        }
        variants[nvar] = std.fmt.bufPrint(&buf, "\u{2581}{s}", .{word}) catch word;
        nvar += 1;
        variants[nvar] = word;
        nvar += 1;
        for (variants[0..nvar]) |v| {
            if (tok.tokenId(v)) |id| {
                found = id;
                break;
            }
        }
        if (found) |id| try ids.append(allocator, id) else sys.print("  (word \"{s}\" not in vocab)\n", .{word});
        first = false;
    }
    if (ids.items.len == 0) return;

    const logits: []f32 = try eng.prefill(ids.items, 0);

    sys.print("  prompt \"{s}\" ({d} tokens) -> top-5:\n", .{ prompt, ids.items.len });
    const used = try allocator.alloc(bool, logits.len);
    defer allocator.free(used);
    @memset(used, false);
    var shown: usize = 0;
    while (shown < 5) : (shown += 1) {
        var best: usize = 0;
        var best_v: f32 = -std.math.inf(f32);
        for (logits, 0..) |v, i| {
            if (!used[i] and v > best_v) {
                best_v = v;
                best = i;
            }
        }
        used[best] = true;
        const txt = if (best < tok.vocabSize()) tok.tokenText(@intCast(best)) else "?";
        sys.print("    {d}. id={d} logit={d:.2} {s}\n", .{ shown + 1, best, best_v, txt });
    }
}

// ---------------------------------------------------------------------------
// run: generate text with a real GGUF model on the ANE.
// ---------------------------------------------------------------------------

const tokenizer_mod = @import("tokenizer.zig");

fn argStr(argv: []const [:0]const u8, name: []const u8) ?[]const u8 {
    for (argv, 0..) |a, i| {
        if (std.mem.eql(u8, a, name) and i + 1 < argv.len) return argv[i + 1];
    }
    return null;
}

fn argF32(argv: []const [:0]const u8, name: []const u8, default: f32) f32 {
    const v = argStr(argv, name) orelse return default;
    return std.fmt.parseFloat(f32, v) catch default;
}

fn cmdRun(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const model_path = argStr(argv, "--model") orelse {
        sys.eprint("usage: anedvd run --model <model.gguf> --prompt \"...\" [--max-tokens N] [--temp T] [--top-k K]\n", .{});
        std.process.exit(2);
    };
    const prompt = argStr(argv, "--prompt") orelse "The capital of France is";
    const max_tokens: u32 = argValue(argv, "--max-tokens", 48);
    const temperature = argF32(argv, "--temp", 0.0);
    const top_k: usize = argValue(argv, "--top-k", 40);
    const chunk: u32 = argValue(argv, "--chunk", 128);
    const top_p = argF32(argv, "--top-p", 1.0);
    const rep_penalty = argF32(argv, "--repeat-penalty", 1.0);
    var fuse = true;
    var rope_hf = false;
    var rope_adj = false;
    for (argv) |a| {
        if (std.mem.eql(u8, a, "--split")) fuse = false;
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
    }

    sys.print("loading {s}\n", .{model_path});
    const t_rt0 = sys.nowNs();
    var loaded = try model_open.open(allocator, model_path, .{
        .progress = true,
        .rope_hf = rope_hf,
        .rope_adjacent = rope_adj,
    });
    defer loaded.deinit();
    const t_rt1 = sys.nowNs();
    const tok = &loaded.tokenizer;
    const cfg = loaded.config;
    sys.print("  {s} ({s}): {d} layers, hidden {d}, vocab {d}\n", .{
        cfg.arch, if (loaded.format == .gguf) "GGUF" else "safetensors", cfg.layers, cfg.hidden, cfg.vocab,
    });
    sys.print("  rope: {s}\n", .{if (cfg.rope_adjacent) "adjacent pairs (llama.cpp NORM)" else "half-split (llama.cpp NEOX)"});
    if (loaded.rt.norms.len > 0 and loaded.rt.norms[0].qkv_bias != null) sys.print("  attention biases: present\n", .{});

    const t_c0 = sys.nowNs();
    var eng = try engine_mod.Engine.init(allocator, loaded.rt, loaded.layers, loaded.head, .{
        .max_seq = argValue(argv, "--max-seq", 2048),
        .verbose = true,
        .fuse_ffn = fuse,
        .chunk = chunk,
    });
    defer eng.deinit();
    const t_c1 = sys.nowNs();
    sys.print("  {d} ANE kernels compiled\n", .{ane.compileCount()});
    sys.print("  startup: weights {d:.2} s + kernels {d:.2} s\n", .{
        @as(f64, @floatFromInt(t_rt1 - t_rt0)) / 1e9,
        @as(f64, @floatFromInt(t_c1 - t_c0)) / 1e9,
    });

    // Prompt formatting: ChatML for instruct models that have the tokens.
    var formatted = std.ArrayList(u8).empty;
    defer formatted.deinit(allocator);
    const im_start = tok.tokenId("<|im_start|>");
    const im_end = tok.tokenId("<|im_end|>");
    if (im_start != null and im_end != null) {
        try formatted.appendSlice(allocator, "<|im_start|>user\n");
        try formatted.appendSlice(allocator, prompt);
        try formatted.appendSlice(allocator, "<|im_end|>\n<|im_start|>assistant\n");
    } else {
        try formatted.appendSlice(allocator, prompt);
    }
    const ids = try tok.encode(allocator, formatted.items, true);
    defer allocator.free(ids);
    sys.print("\nprompt ({d} tokens): {s}\n---\n", .{ ids.len, formatted.items });

    // A/B: the same prompt through the per-token path must give the same logits.
    var ab = false;
    for (argv) |a| if (std.mem.eql(u8, a, "--ab")) {
        ab = true;
    };
    if (ab) {
        // Both paths return the engine's internal logits buffer, so the first
        // result must be COPIED before the second run overwrites it. Comparing
        // the two slices directly compares a buffer with itself and always
        // reports zero -- which is exactly how the prefill attention layout bug
        // survived an "A/B bit-identical" claim.
        var seq_logits: []f32 = undefined;
        for (ids, 0..) |id, pos| {
            const l = try eng.forward(id, @intCast(pos));
            if (pos + 1 == ids.len) {
                seq_logits = try allocator.dupe(f32, l);
            }
        }
        defer allocator.free(seq_logits);
        const batch_logits = try eng.prefill(ids, 0);
        var max_d: f32 = 0;
        var argmax_seq: u32 = 0;
        var argmax_batch: u32 = 0;
        for (seq_logits, batch_logits, 0..) |a, b, i| {
            max_d = @max(max_d, @abs(a - b));
            if (a > seq_logits[argmax_seq]) argmax_seq = @intCast(i);
            if (b > batch_logits[argmax_batch]) argmax_batch = @intCast(i);
        }
        sys.print("A/B sequential vs batched: max|diff| = {e:.6}, argmax {d} vs {d} ({s})\n", .{
            max_d,
            argmax_seq,
            argmax_batch,
            if (max_d < 1e-3 and argmax_seq == argmax_batch) "ok" else "MISMATCH",
        });
    }

    // Generation goes through the shared session so the CLI, the HTTP API and
    // the WebUI all sample identically.
    var session = generate_mod.Session.init(allocator, &eng, tok);
    defer session.deinit();
    session.stopOnEos();
    const params = generate_mod.Params{
        .max_tokens = max_tokens,
        .sampler = .{ .temperature = temperature, .top_k = top_k, .top_p = top_p, .repetition_penalty = rep_penalty },
    };
    const repeat: u32 = @max(1, argValue(argv, "--repeat", 1));
    if (repeat > 1) sys.print("\n", .{});
    var samples = std.ArrayList(f64).empty;
    defer samples.deinit(allocator);
    var stats: generate_mod.Stats = .{};
    // Wall clock of the whole generation phase. This used to be overwritten with
    // the last iteration's end time, which made it zero for --repeat 1 and made
    // the "ANE share of wall time" line print 0%.
    const t_gen0 = sys.nowNs();
    for (0..repeat) |_| {
        session.reset();
        stats = try session.generate(ids, params, .{ .func = if (repeat == 1) stdoutEmit else nullEmit });
        try samples.append(allocator, stats.decodeToksPerSec());
    }
    const t_end = sys.nowNs();
    if (repeat > 1) {
        std.mem.sort(f64, samples.items, {}, comptime std.sort.asc(f64));
        const median = samples.items[samples.items.len / 2];
        var sum: f64 = 0;
        for (samples.items) |v| sum += v;
        sys.print("\n[repeat {d}] decode tok/s: min {d:.1} median {d:.1} max {d:.1} mean {d:.1}\n", .{
            repeat,
            samples.items[0],
            median,
            samples.items[samples.items.len - 1],
            sum / @as(f64, @floatFromInt(samples.items.len)),
        });
    }

    const total_wall = t_end - t_gen0;
    // With --repeat the per-run numbers below would describe only the last run,
    // so print the summary and stop.
    if (repeat > 1) {
        sys.print("stop: {s} (last run), ANE {d:.1} ms/token\n", .{
            stats.stop_reason.toString(),
            if (eng.stats.tokens > 0) eng.stats.aneMs() / @as(f64, @floatFromInt(eng.stats.tokens)) else 0,
        });
        return;
    }
    sys.print("stop: {s}\n", .{stats.stop_reason.toString()});
    sys.print("prefill: {d} tokens in {d:.2} s ({d:.1} tok/s; ANE {d:.2} s, CPU {d:.2} s)\n", .{
        stats.prompt_tokens,
        @as(f64, @floatFromInt(stats.prefill_ns)) / 1e9,
        if (stats.prefill_ns > 0) @as(f64, @floatFromInt(stats.prompt_tokens)) / (@as(f64, @floatFromInt(stats.prefill_ns)) / 1e9) else 0,
        @as(f64, @floatFromInt(stats.prefill_ane_ns)) / 1e9,
        @as(f64, @floatFromInt(stats.prefill_ns -| stats.prefill_ane_ns)) / 1e9,
    });
    sys.print("decode: {d} tokens in {d:.2} s ({d:.1} tok/s; ANE {d:.0}%, CPU {d:.0}%)\n", .{
        stats.completion_tokens,
        @as(f64, @floatFromInt(stats.decode_ns)) / 1e9,
        stats.decodeToksPerSec(),
        if (stats.decode_ns > 0) 100.0 * @as(f64, @floatFromInt(stats.decode_ane_ns)) / @as(f64, @floatFromInt(stats.decode_ns)) else 0,
        if (stats.decode_ns > 0) 100.0 - 100.0 * @as(f64, @floatFromInt(stats.decode_ane_ns)) / @as(f64, @floatFromInt(stats.decode_ns)) else 0,
    });
    sys.print("ANE: {d} evals for {d} tokens ({d:.1} kernels/token), {d:.1} ms total, {d:.2} ms/token\n", .{
        eng.stats.ane_evals,
        eng.stats.tokens,
        if (eng.stats.tokens > 0) @as(f64, @floatFromInt(eng.stats.ane_evals)) / @as(f64, @floatFromInt(eng.stats.tokens)) else 0,
        eng.stats.aneMs(),
        if (eng.stats.tokens > 0) eng.stats.aneMs() / @as(f64, @floatFromInt(eng.stats.tokens)) else 0,
    });
    sys.print("ANE share of wall time: {d:.0}%\n", .{
        if (total_wall > 0) 100.0 * @as(f64, @floatFromInt(eng.stats.ane_eval_ns)) / @as(f64, @floatFromInt(total_wall)) else 0,
    });
    if (stats.prompt_tokens > 0) {
        const p: f64 = @floatFromInt(stats.prompt_tokens);
        sys.print("prefill CPU phases per token: convert {d:.2} ms, rope+cache {d:.2} ms, attn {d:.2} ms, norm {d:.2} ms, stage {d:.2} ms\n", .{
            @as(f64, @floatFromInt(eng.stats.pf_convert_ns)) / 1e6 / p,
            @as(f64, @floatFromInt(eng.stats.pf_rope_ns)) / 1e6 / p,
            @as(f64, @floatFromInt(eng.stats.pf_attn_ns)) / 1e6 / p,
            @as(f64, @floatFromInt(eng.stats.pf_norm_ns)) / 1e6 / p,
            @as(f64, @floatFromInt(eng.stats.pf_stage_ns)) / 1e6 / p,
        });
    }
    if (stats.completion_tokens > 0) {
        const n: f64 = @floatFromInt(stats.completion_tokens);
        sys.print("sampling: {d:.2} ms/token, candidates avg {d:.0} max {d} of {d} vocab\n", .{
            @as(f64, @floatFromInt(stats.sample_ns)) / 1e6 / n,
            @as(f64, @floatFromInt(stats.sample_candidates_total)) / n,
            stats.sample_candidates_max,
            cfg.vocab,
        });
    }
    const tot = eng.stats.tokens;
    if (tot > 0) {
        const t: f64 = @floatFromInt(tot);
        sys.print("ANE per-token split: qkv {d:.2} ms, o {d:.2} ms, ffn {d:.2} ms, lm_head {d:.2} ms\n", .{
            eng.stats.nodeMs(.qkv) / t,
            eng.stats.nodeMs(.o) / t,
            eng.stats.nodeMs(.ffn) / t,
            eng.stats.nodeMs(.head) / t,
        });
        sys.print("  qkv staging: write {d:.2} ms, read {d:.2} ms per token\n", .{
            @as(f64, @floatFromInt(eng.stats.qkv_write_ns)) / 1e6 / t,
            @as(f64, @floatFromInt(eng.stats.qkv_read_ns)) / 1e6 / t,
        });
        sys.print("  counters: tokens {d}, node evals qkv {d} o {d} ffn {d} head {d}\n", .{
            eng.stats.tokens,
            eng.stats.node_evals[0],
            eng.stats.node_evals[1],
            eng.stats.node_evals[2],
            eng.stats.node_evals[3],
        });
    }
}

// ---------------------------------------------------------------------------
// cpu: pure-CPU reference generation, used to validate model handling without
// compiling any ANE kernels.
// ---------------------------------------------------------------------------

fn cmdCpu(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const model_path = argStr(argv, "--model") orelse {
        sys.eprint("usage: anedvd cpu --model <m.gguf> --prompt \"...\" [--rope-hf] [--chat] [--max-tokens N]\n", .{});
        std.process.exit(2);
    };
    const prompt = argStr(argv, "--prompt") orelse "The capital of France is";
    const max_tokens: u32 = argValue(argv, "--max-tokens", 24);
    var rope_hf = false;
    var rope_adj = false;
    var chat = false;
    for (argv) |a| {
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
        if (std.mem.eql(u8, a, "--chat")) chat = true;
    }

    // Both formats, via the same loader `verify` uses for its reference.
    var mw = try cloneForReference(allocator, model_path, std.math.maxInt(usize));
    defer mw.deinit();
    if (rope_hf) mw.config.rope_adjacent = false;
    if (rope_adj) mw.config.rope_adjacent = true;
    const cfg = mw.config;
    var tok_guard: ?*gguf.Gguf = null;
    var tok = try openTokenizer(allocator, model_path, &tok_guard);
    defer tok.deinit();
    defer closeTokenizerGuard(allocator, tok_guard);
    sys.print("cpu reference: {s} hidden={d} layers={d} heads={d}/{d} rope_adjacent={}\n", .{
        cfg.arch, cfg.hidden, cfg.layers, cfg.heads, cfg.kv_heads, cfg.rope_adjacent,
    });

    var text = std.ArrayList(u8).empty;
    defer text.deinit(allocator);
    const has_chatml = tok.tokenId("<|im_start|>") != null and tok.tokenId("<|im_end|>") != null;
    if (chat and has_chatml) {
        try text.appendSlice(allocator, "<|im_start|>user\n");
        try text.appendSlice(allocator, prompt);
        try text.appendSlice(allocator, "<|im_end|>\n<|im_start|>assistant\n");
    } else {
        try text.appendSlice(allocator, prompt);
    }
    const ids = try tok.encode(allocator, text.items, true);
    defer allocator.free(ids);

    const L: usize = cfg.layers;
    var st = RefState{ .k = try allocator.alloc([]f16, L), .v = try allocator.alloc([]f16, L) };
    defer {
        for (st.k) |c| allocator.free(c);
        for (st.v) |c| allocator.free(c);
        allocator.free(st.k);
        allocator.free(st.v);
    }
    for (0..L) |i| {
        st.k[i] = try allocator.alloc(f16, 1024 * cfg.kvDim());
        st.v[i] = try allocator.alloc(f16, 1024 * cfg.kvDim());
        @memset(st.k[i], 0);
        @memset(st.v[i], 0);
    }

    sys.print("prompt ({d} tokens): ", .{ids.len});
    const pbytes = try tok.decode(allocator, ids);
    defer allocator.free(pbytes);
    sys.print("{s}\n---\n", .{pbytes});

    const t0 = sys.nowNs();
    var logits: []f32 = undefined;
    for (ids, 0..) |id, pos| {
        if (pos > 0) allocator.free(logits);
        logits = try refForward(allocator, &mw, &st, id, @intCast(pos), cfg.layers);
    }
    defer allocator.free(logits);
    const t1 = sys.nowNs();

    const eos = tok.eosId();
    var produced: u32 = 0;
    var pos: u32 = @intCast(ids.len);
    while (produced < max_tokens) : (produced += 1) {
        const next = cpu.argmax(logits);
        if (eos != null and next == eos.?) break;
        const bytes = try tok.tokenBytes(allocator, next);
        defer allocator.free(bytes);
        sys.writeAll(1, bytes);
        if (pos > 0) allocator.free(logits);
        logits = try refForward(allocator, &mw, &st, next, pos, cfg.layers);
        pos += 1;
    }
    const t2 = sys.nowNs();
    sys.print("\n---\ncpu prefill {d:.2} s, decode {d:.2} s ({d:.1} tok/s)\n", .{
        @as(f64, @floatFromInt(t1 - t0)) / 1e9,
        @as(f64, @floatFromInt(t2 - t1)) / 1e9,
        @as(f64, @floatFromInt(produced)) / (@as(f64, @floatFromInt(t2 - t1)) / 1e9),
    });
}

// ---------------------------------------------------------------------------
// serve: OpenAI- and Anthropic-compatible HTTP API plus the built-in WebUI.
// ---------------------------------------------------------------------------

const server_mod = @import("server.zig");
const model_open = @import("model_open.zig");
const generate_mod = @import("generate.zig");

fn stdoutEmit(ctx: ?*anyopaque, piece: []const u8, token_id: u32) bool {
    _ = ctx;
    _ = token_id;
    sys.writeAll(1, piece);
    return true;
}

/// Discards output: used by --repeat so only the summary is printed.
fn nullEmit(ctx: ?*anyopaque, piece: []const u8, token_id: u32) bool {
    _ = ctx;
    _ = piece;
    _ = token_id;
    return true;
}

fn fileStem(path: []const u8) []const u8 {
    const base = std.fs.path.basename(path);
    const ext = std.fs.path.extension(base);
    return base[0 .. base.len - ext.len];
}

fn cmdServe(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const model_path = argStr(argv, "--model") orelse {
        sys.eprint("usage: anedvd serve --model <model.gguf> [--host 127.0.0.1] [--port 8080] [--name ID] [--system \"...\"]\n", .{});
        std.process.exit(2);
    };
    const host = argStr(argv, "--host") orelse "127.0.0.1";
    const port: u16 = @intCast(argValue(argv, "--port", 8080));
    const model_name = argStr(argv, "--name") orelse model_open.modelName(model_path);
    const system = argStr(argv, "--system");
    const max_seq: u32 = argValue(argv, "--max-seq", 2048);
    const default_max_tokens: u32 = argValue(argv, "--max-tokens", 512);
    const chunk: u32 = argValue(argv, "--chunk", 128);
    const top_p = argF32(argv, "--top-p", 1.0);
    const rep_penalty = argF32(argv, "--repeat-penalty", 1.0);
    var fuse = true;
    var rope_hf = false;
    var rope_adj = false;
    for (argv) |a| {
        if (std.mem.eql(u8, a, "--split")) fuse = false;
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
    }

    sys.print("loading {s}\n", .{model_path});
    var loaded = try model_open.open(allocator, model_path, .{
        .progress = true,
        .rope_hf = rope_hf,
        .rope_adjacent = rope_adj,
    });
    defer loaded.deinit();
    const tok = &loaded.tokenizer;
    const cfg = loaded.config;
    sys.print("  {s} ({s}): {d} layers, hidden {d}, vocab {d}, rope {s}\n", .{
        cfg.arch,                                            if (loaded.format == .gguf) "GGUF" else "safetensors", cfg.layers, cfg.hidden, cfg.vocab,
        if (cfg.rope_adjacent) "adjacent" else "half-split",
    });

    var eng = try engine_mod.Engine.init(allocator, loaded.rt, loaded.layers, loaded.head, .{
        .max_seq = max_seq,
        .verbose = true,
        .fuse_ffn = fuse,
        .chunk = chunk,
    });
    defer eng.deinit();
    sys.print("  {d} ANE kernels compiled\n", .{ane.compileCount()});

    var session = generate_mod.Session.init(allocator, &eng, tok);
    defer session.deinit();
    session.stopOnEos();

    var srv = server_mod.Server{
        .allocator = allocator,
        .session = &session,
        .opts = .{
            .host = host,
            .port = port,
            .model_name = model_name,
            .default_system = system,
            .default_max_tokens = default_max_tokens,
            .default_top_p = top_p,
            .default_repetition_penalty = rep_penalty,
        },
    };
    try srv.run();
}

/// Measures how the per-eval cost grows with the activation width. The ANE
/// reads the weights once per eval regardless of width, so a decode-shaped
/// kernel (width 1) and a prefill-shaped one (width 32..128) should cost almost
/// the same — which is what makes batched prefill worth implementing.
fn cmdWidthSweep(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const size = argValue(argv, "--size", 2048);
    const iters = argValue(argv, "--iters", 30);
    sys.print("ANE conv cost vs activation width ({d} -> {d}, fp16, weights read once)\n", .{ size, size });
    sys.print("{s:>7} {s:>12} {s:>12} {s:>12}\n", .{ "width", "us/eval", "vs w=1", "GFLOP/s" });
    var base_us: f64 = 0;
    for ([_]u32{ 1, 8, 32, 64, 128 }) |w| {
        const r = runMatmulProbeWidth(allocator, size, size, iters, w) catch |e| {
            sys.print("{d:>7} FAILED: {s}\n", .{ w, @errorName(e) });
            continue;
        };
        if (w == 1) base_us = r.eval_us;
        const gflops = 2.0 * @as(f64, @floatFromInt(size)) * @as(f64, @floatFromInt(size)) * @as(f64, @floatFromInt(w)) / 1e9 / (r.eval_us / 1e6);
        sys.print("{d:>7} {d:>12.2} {d:>11.2}x {d:>12.1}\n", .{ w, r.eval_us, if (base_us > 0) r.eval_us / base_us else 1, gflops });
    }
}

// ---------------------------------------------------------------------------
// chat: interactive multi-turn REPL.
// ---------------------------------------------------------------------------

const History = struct {
    allocator: std.mem.Allocator,
    turns: std.ArrayList(generate_mod.Message) = .empty,

    fn deinit(self: *History) void {
        for (self.turns.items) |t| self.allocator.free(t.content);
        self.turns.deinit(self.allocator);
    }
    fn add(self: *History, role: generate_mod.Role, text: []const u8) !void {
        try self.turns.append(self.allocator, .{ .role = role, .content = try self.allocator.dupe(u8, text) });
    }
    fn clear(self: *History) void {
        for (self.turns.items) |t| self.allocator.free(t.content);
        self.turns.clearRetainingCapacity();
    }
};

/// Read one line from stdin. Returns null at EOF.
fn readLine(allocator: std.mem.Allocator, prompt: []const u8) !?[]u8 {
    sys.writeAll(1, prompt);
    var out: std.ArrayList(u8) = .empty;
    var byte: [1]u8 = undefined;
    while (true) {
        const n = std.c.read(0, &byte, 1);
        if (n <= 0) {
            if (out.items.len == 0) {
                out.deinit(allocator);
                return null;
            }
            break;
        }
        if (byte[0] == '\n') break;
        try out.append(allocator, byte[0]);
    }
    return try out.toOwnedSlice(allocator);
}

fn cmdChat(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const model_path = argStr(argv, "--model") orelse {
        sys.eprint("usage: anedvd chat --model <model.gguf|hf-dir> [--system \"...\"] [--temp T] [--top-p P] [--repeat-penalty R]\n", .{});
        std.process.exit(2);
    };
    const system = argStr(argv, "--system");
    const max_tokens: u32 = argValue(argv, "--max-tokens", 256);
    const chunk: u32 = argValue(argv, "--chunk", 128);
    var temperature = argF32(argv, "--temp", 0.7);
    var top_p = argF32(argv, "--top-p", 0.9);
    var rep_penalty = argF32(argv, "--repeat-penalty", 1.15);
    var rope_hf = false;
    var rope_adj = false;
    for (argv) |a| {
        if (std.mem.eql(u8, a, "--rope-hf")) rope_hf = true;
        if (std.mem.eql(u8, a, "--rope-adjacent")) rope_adj = true;
    }

    sys.print("loading {s}\n", .{model_path});
    var loaded = try model_open.open(allocator, model_path, .{ .progress = true, .rope_hf = rope_hf, .rope_adjacent = rope_adj });
    defer loaded.deinit();
    const tok = &loaded.tokenizer;
    const cfg = loaded.config;
    sys.print("  {s} ({s}): {d} layers, hidden {d}, vocab {d}\n", .{
        cfg.arch, if (loaded.format == .gguf) "GGUF" else "safetensors", cfg.layers, cfg.hidden, cfg.vocab,
    });

    var eng = try engine_mod.Engine.init(allocator, loaded.rt, loaded.layers, loaded.head, .{
        .max_seq = @intCast(argValue(argv, "--max-seq", 2048)),
        .verbose = true,
        .chunk = chunk,
    });
    defer eng.deinit();
    sys.print("  {d} ANE kernels compiled\n", .{ane.compileCount()});

    var session = generate_mod.Session.init(allocator, &eng, tok);
    defer session.deinit();
    session.stopOnEos();

    var history = History{ .allocator = allocator };
    defer history.deinit();

    sys.print("\nready. /help for commands, /exit to quit.\n", .{});
    while (true) {
        const line = (try readLine(allocator, "\nyou> ")) orelse break;
        defer allocator.free(line);
        const text = std.mem.trim(u8, line, " \t");
        if (text.len == 0) continue;

        if (text[0] == '/') {
            if (std.mem.eql(u8, text, "/exit") or std.mem.eql(u8, text, "/quit")) break;
            if (std.mem.eql(u8, text, "/reset")) {
                history.clear();
                sys.print("history cleared\n", .{});
                continue;
            }
            if (std.mem.eql(u8, text, "/help")) {
                sys.print("/reset  clear the conversation\n/temp X set temperature (0 = greedy)\n/topp X set top-p\n/rep X  set repetition penalty\n/exit   quit\n", .{});
                continue;
            }
            if (std.mem.startsWith(u8, text, "/temp ")) {
                temperature = std.fmt.parseFloat(f32, text[6..]) catch temperature;
                sys.print("temperature = {d:.2}\n", .{temperature});
                continue;
            }
            if (std.mem.startsWith(u8, text, "/topp ")) {
                top_p = std.fmt.parseFloat(f32, text[6..]) catch top_p;
                sys.print("top_p = {d:.2}\n", .{top_p});
                continue;
            }
            if (std.mem.startsWith(u8, text, "/rep ")) {
                rep_penalty = std.fmt.parseFloat(f32, text[5..]) catch rep_penalty;
                sys.print("repetition_penalty = {d:.2}\n", .{rep_penalty});
                continue;
            }
            sys.print("unknown command; /help\n", .{});
            continue;
        }

        try history.add(.user, text);
        const prompt = try session.formatChat(allocator, history.turns.items, system);
        defer allocator.free(prompt);
        const ids = try tok.encode(allocator, prompt, true);
        defer allocator.free(ids);

        var reply: std.ArrayList(u8) = .empty;
        defer reply.deinit(allocator);
        const collector = ChatSink{ .out = &reply, .allocator = allocator };
        const params = generate_mod.Params{
            .max_tokens = max_tokens,
            .sampler = .{ .temperature = temperature, .top_p = top_p, .repetition_penalty = rep_penalty },
        };
        sys.print("\n", .{});
        const stats = try session.generate(ids, params, .{ .ctx = @constCast(&collector), .func = chatEmit });
        try history.add(.assistant, reply.items);
        sys.print("\n[{d} tokens, {d:.1} tok/s, {s}, prompt {d} ({d} reused from cache)]\n", .{
            stats.completion_tokens,
            stats.decodeToksPerSec(),
            stats.stop_reason.toString(),
            stats.prompt_tokens,
            stats.prefill_reused,
        });
    }
    sys.print("bye\n", .{});
}

const ChatSink = struct {
    out: *std.ArrayList(u8),
    allocator: std.mem.Allocator,
};

fn chatEmit(ctx: ?*anyopaque, piece: []const u8, token_id: u32) bool {
    _ = token_id;
    const sink: *ChatSink = @ptrCast(@alignCast(ctx.?));
    sys.writeAll(1, piece);
    sink.out.appendSlice(sink.allocator, piece) catch return false;
    return true;
}

/// Micro-benchmark for the CPU attention path, which dominates decode at long
/// context. Reports the dot-product, softmax and value-accumulation shares.
fn cmdAttnBench(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    const ctx: usize = argValue(argv, "--ctx", 1024);
    const heads: u32 = argValue(argv, "--heads", 14);
    const kv_heads: u32 = argValue(argv, "--kv-heads", 2);
    const hd: u32 = argValue(argv, "--head-dim", 64);
    const iters: u32 = argValue(argv, "--iters", 200);
    const kv_dim: usize = @as(usize, kv_heads) * hd;

    const k = try allocator.alloc(f16, ctx * kv_dim);
    defer allocator.free(k);
    const v = try allocator.alloc(f16, ctx * kv_dim);
    defer allocator.free(v);
    const q = try allocator.alloc(f32, @as(usize, heads) * hd);
    defer allocator.free(q);
    const out = try allocator.alloc(f32, @as(usize, heads) * hd);
    defer allocator.free(out);
    const scores = try allocator.alloc(f32, ctx);
    defer allocator.free(scores);
    var seed: u32 = 7;
    for (k) |*x| {
        seed = seed *% 1664525 +% 1013904223;
        x.* = @floatCast(@as(f32, @floatFromInt(seed >> 8)) / 8388608.0 - 1.0);
    }
    for (v) |*x| {
        seed = seed *% 1664525 +% 1013904223;
        x.* = @floatCast(@as(f32, @floatFromInt(seed >> 8)) / 8388608.0 - 1.0);
    }
    for (q) |*x| {
        seed = seed *% 1664525 +% 1013904223;
        x.* = @as(f32, @floatFromInt(seed >> 8)) / 8388608.0 - 1.0;
    }

    // Whole attention.
    cpu.attentionDecode(out, q, k, v, ctx, heads, kv_heads, hd, scores);
    var t0 = sys.nowNs();
    for (0..iters) |_| cpu.attentionDecode(out, q, k, v, ctx, heads, kv_heads, hd, scores);
    const full_ns = (sys.nowNs() - t0) / iters;

    // Dot products only (no softmax, no AV).
    const scale = 1.0 / @sqrt(@as(f32, @floatFromInt(hd)));
    const group = heads / kv_heads;
    t0 = sys.nowNs();
    for (0..iters) |_| {
        for (0..heads) |h| {
            const kvh = h / group;
            const q_h = q[h * hd ..][0..hd];
            for (0..ctx) |t| {
                const k_t = k[t * kv_dim + kvh * hd ..][0..hd];
                scores[t] = cpu.dotF32F16(q_h, k_t) * scale;
            }
        }
    }
    const dot_ns = (sys.nowNs() - t0) / iters;

    // Softmax only.
    t0 = sys.nowNs();
    for (0..iters) |_| {
        for (0..heads) |_| cpu.softmax(scores);
    }
    const soft_ns = (sys.nowNs() - t0) / iters;

    const full_us = @as(f64, @floatFromInt(full_ns)) / 1000.0;
    const dot_us = @as(f64, @floatFromInt(dot_ns)) / 1000.0;
    const soft_us = @as(f64, @floatFromInt(soft_ns)) / 1000.0;
    const rest_us = if (full_ns > dot_ns + soft_ns)
        @as(f64, @floatFromInt(full_ns - dot_ns - soft_ns)) / 1000.0
    else
        0;
    sys.print("CPU attention at ctx={d} (heads {d}/{d}, head_dim {d})\n", .{ ctx, heads, kv_heads, hd });
    sys.print("  full        {d:>9.1} us\n", .{full_us});
    sys.print("  dot only    {d:>9.1} us  ({d:.0}%)\n", .{ dot_us, 100.0 * dot_us / full_us });
    sys.print("  softmax     {d:>9.1} us  ({d:.0}%)\n", .{ soft_us, 100.0 * soft_us / full_us });
    sys.print("  AV + rest   {d:>9.1} us  ({d:.0}%)\n", .{ rest_us, 100.0 * rest_us / full_us });
}

/// Time each of a real model's layer-0 kernels individually and report the
/// achieved weight bandwidth. Aggregated per-token numbers hide which kernel is
/// off; this is the measurement that says whether a kernel is bandwidth bound
/// (~12-30 GB/s here) or has some other problem.
fn cmdKernels(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    if (argv.len < 3) {
        sys.eprint("usage: anedvd kernels <model.gguf|hf-dir> [--iters K] [--chunk N]\n", .{});
        std.process.exit(2);
    }
    const path = argv[2];
    const iters: u32 = argValue(argv, "--iters", 100);
    const chunk: u32 = argValue(argv, "--chunk", 128);

    var loaded = try model_open.open(allocator, path, .{ .progress = false });
    defer loaded.deinit();
    const cfg = loaded.config;

    // Layer 0 weights are needed both for the kernel weights and to size the
    // byte counters.
    var m0 = try loaded.layers.load(allocator, 0);
    defer m0.deinit(allocator);

    var eng = try engine_mod.Engine.init(allocator, loaded.rt, loaded.layers, loaded.head, .{
        .max_seq = 64,
        .verbose = false,
        .chunk = chunk,
    });
    defer eng.deinit();

    sys.print("per-kernel timing: {s}, chunk {d}, {d} iterations\n", .{ path, chunk, iters });
    // Warm up once so the first-token cost (KV growth, cache effects) is out.
    _ = try eng.forward(1, 0);
    eng.stats = .{};
    const t0 = sys.nowNs();
    for (0..iters) |_| {
        _ = try eng.forward(1, 0);
    }
    const full_us = @as(f64, @floatFromInt((sys.nowNs() - t0) / iters)) / 1000.0;

    // nodeMs accumulates over ALL layers, so a per-layer comparison has to
    // divide by layers as well as by tokens. Getting this wrong made every
    // kernel look ~24x slower than the standalone probe.
    const t = eng.stats.tokens;
    if (t > 0) {
        const evals_per_token: f64 = @floatFromInt(@max(eng.stats.node_evals[0], 1));
        const tf: f64 = @floatFromInt(t);
        const layers: f64 = @floatFromInt(@max(cfg.layers, 1));
        const per_layer_evals = evals_per_token / tf / layers; // 1 normally
        const rows = [_]struct { name: []const u8, ms: f64, bytes: f64 }{
            .{ .name = "qkv", .ms = eng.stats.nodeMs(.qkv) / tf / layers, .bytes = @floatFromInt(@as(u64, cfg.qkvDim()) * cfg.hidden * 2) },
            .{ .name = "o", .ms = eng.stats.nodeMs(.o) / tf / layers, .bytes = @floatFromInt(@as(u64, cfg.hidden) * cfg.qDim() * 2) },
            .{ .name = "ffn", .ms = eng.stats.nodeMs(.ffn) / tf / layers, .bytes = @floatFromInt((2 * @as(u64, cfg.inter) * cfg.hidden + @as(u64, cfg.hidden) * cfg.inter) * 2) },
            .{ .name = "lm_head", .ms = eng.stats.nodeMs(.head) / tf, .bytes = @floatFromInt(@as(u64, cfg.vocab) * cfg.hidden * 2) },
        };
        sys.print("{s:<10} {s:>12} {s:>12} {s:>10} {s:>14}\n", .{ "kernel", "ms/1 layer", "ms/1 eval", "x layers", "GB/s" });
        for (rows) |r| {
            const per_eval = r.ms / per_layer_evals;
            const gbs = if (per_eval > 0) r.bytes / (per_eval / 1000.0) / 1e9 else 0;
            const n_layers = if (std.mem.eql(u8, r.name, "lm_head")) 1 else cfg.layers;
            const per_token = r.ms * @as(f64, @floatFromInt(n_layers));
            _ = per_token;
            sys.print("{s:<10} {d:>12.3} {d:>12.3} {d:>10} {d:>14.1}\n", .{ r.name, r.ms, per_eval, n_layers, gbs });
        }
        sys.print("{s:<10} {d:>11.2} {s:>11} {s:>8} {s:>13}\n", .{ "TOTAL", full_us / 1000.0, "", "", "" });
    }
    sys.print("\nms/head is one layer's eval (qkv/o/ffn run once per layer) or one lm_head eval;\nGB/s is that kernel's weights divided by that time.\n", .{});
}

/// Whole-model cross-check: run the prompt through the ANE engine and through
/// the pure-CPU reference and compare the final logits.
///
/// `check` only exercises layer 0's kernels in isolation, which is exactly why
/// a transposed activation layout in the prefill attention could produce garbage
/// for Qwen2.5-1.5B while every per-kernel check passed: the bug lived in the
/// hand-off between kernels, not inside any one of them. This command is the one
/// that catches that class of mistake.
fn cmdVerify(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    if (argv.len < 3) {
        sys.eprint("usage: anedvd verify <model> [--prompt \"...\"] [--layers N]\n", .{});
        std.process.exit(2);
    }
    const path = argv[2];
    const prompt = argStr(argv, "--prompt") orelse "The capital of France is";
    const layers_cap: u32 = argValue(argv, "--layers", 0);

    var loaded = try model_open.open(allocator, path, .{ .progress = false });
    defer loaded.deinit();
    const cfg = loaded.config;
    const layers: usize = if (layers_cap > 0) @min(layers_cap, cfg.layers) else cfg.layers;

    sys.print("verify {s}: {d} layers, hidden {d}, heads {d}/{d}, head_dim {d}\n", .{
        path, layers, cfg.hidden, cfg.heads, cfg.kv_heads, cfg.head_dim,
    });

    // The CPU reference needs its own copy of the weights: the engine takes
    // ownership of the ones in `loaded`.
    var ref_mw = try cloneForReference(allocator, path, layers);
    defer ref_mw.deinit();

    var eng = try engine_mod.Engine.init(allocator, loaded.rt, loaded.layers, loaded.head, .{
        .max_seq = 1024,
        .verbose = false,
        .chunk = 128,
    });
    defer eng.deinit();
    if (layers < cfg.layers) eng.stopAfterLayer(@intCast(layers));

    const ids = try loaded.tokenizer.encode(allocator, prompt, true);
    defer allocator.free(ids);

    // ANE prefill, and then one decode step on top of it: the two paths use
    // different kernels (a chunk-wide pass vs a single column), so both need
    // checking. Each result is COPIED out, because the engine returns its own
    // logits buffer.
    const ane_prefill = try allocator.dupe(f32, try eng.prefill(ids, 0));
    defer allocator.free(ane_prefill);
    const ane_decode = try allocator.dupe(f32, try eng.forward(7, @intCast(ids.len)));
    defer allocator.free(ane_decode);

    // CPU reference: one token at a time, same prompt.
    var st = RefState{ .k = try allocator.alloc([]f16, layers), .v = try allocator.alloc([]f16, layers) };
    defer {
        for (st.k) |c| allocator.free(c);
        for (st.v) |c| allocator.free(c);
        allocator.free(st.k);
        allocator.free(st.v);
    }
    for (0..layers) |i| {
        st.k[i] = try allocator.alloc(f16, 1024 * cfg.kvDim());
        st.v[i] = try allocator.alloc(f16, 1024 * cfg.kvDim());
        @memset(st.k[i], 0);
        @memset(st.v[i], 0);
    }
    var cpu_logits: []f32 = undefined;
    for (ids, 0..) |id, pos| {
        if (pos > 0) allocator.free(cpu_logits);
        cpu_logits = try refForward(allocator, &ref_mw, &st, id, @intCast(pos), layers);
    }
    const cpu_decode: []f32 = try refForward(allocator, &ref_mw, &st, 7, @intCast(ids.len), layers);
    defer allocator.free(cpu_decode);
    defer allocator.free(cpu_logits);

    const prefill = compareLogits(ane_prefill, cpu_logits);
    const decode = compareLogits(ane_decode, cpu_decode);
    sys.print("  prefill: max|ANE - CPU| = {e:.5}  (max|logit| {e:.3}, rel {e:.5})  argmax {d} \"{s}\" vs {d} \"{s}\"\n", .{
        prefill.max_abs,
        prefill.max_mag,
        prefill.rel,
        prefill.argmax_a,
        loaded.tokenizer.tokenText(prefill.argmax_a),
        prefill.argmax_b,
        loaded.tokenizer.tokenText(prefill.argmax_b),
    });
    sys.print("  decode:  max|ANE - CPU| = {e:.5}  (max|logit| {e:.3}, rel {e:.5})  argmax {d} \"{s}\" vs {d} \"{s}\"\n", .{
        decode.max_abs,
        decode.max_mag,
        decode.rel,
        decode.argmax_a,
        loaded.tokenizer.tokenText(decode.argmax_a),
        decode.argmax_b,
        loaded.tokenizer.tokenText(decode.argmax_b),
    });
    const ok = prefill.rel < 0.05 and prefill.argmax_a == prefill.argmax_b and
        decode.rel < 0.05 and decode.argmax_a == decode.argmax_b;
    sys.print("  RESULT: {s}\n", .{if (ok) "MATCH" else "MISMATCH"});
    if (!ok) std.process.exit(1);
}

const LogitDiff = struct {
    max_abs: f32,
    max_mag: f32,
    rel: f32,
    argmax_a: u32,
    argmax_b: u32,
};

fn compareLogits(a: []const f32, b: []const f32) LogitDiff {
    var d = LogitDiff{ .max_abs = 0, .max_mag = 0, .rel = 0, .argmax_a = 0, .argmax_b = 0 };
    for (a, b, 0..) |x, y, i| {
        d.max_abs = @max(d.max_abs, @abs(x - y));
        d.max_mag = @max(d.max_mag, @abs(y));
        if (x > a[d.argmax_a]) d.argmax_a = @intCast(i);
        if (y > b[d.argmax_b]) d.argmax_b = @intCast(i);
    }
    d.rel = if (d.max_mag > 0) d.max_abs / d.max_mag else d.max_abs;
    return d;
}

/// Open the tokenizer for a model path, whichever format it is.
///
/// For GGUF this keeps the mapping open in `guard`: Tokenizer.fromGguf keeps
/// slices into the mapped file for its vocabulary, so releasing the map here
/// would leave the tokenizer pointing at unmapped memory (a segfault the moment
/// it is used, which is how this was found).
fn openTokenizer(allocator: std.mem.Allocator, path: []const u8, guard: *?*gguf.Gguf) !tokenizer_mod.Tokenizer {
    guard.* = null;
    if (std.mem.endsWith(u8, path, ".gguf")) {
        const g = try allocator.create(gguf.Gguf);
        errdefer allocator.destroy(g);
        g.* = try gguf.Gguf.load(allocator, path);
        errdefer g.deinit();
        const tok = try tokenizer_mod.Tokenizer.fromGguf(allocator, g);
        guard.* = g;
        return tok;
    }
    const tok_path = try std.fs.path.join(allocator, &.{ path, "tokenizer.json" });
    defer allocator.free(tok_path);
    return tokenizer_mod.Tokenizer.fromTokenizerJson(allocator, tok_path);
}

fn closeTokenizerGuard(allocator: std.mem.Allocator, guard: ?*gguf.Gguf) void {
    if (guard) |g| {
        g.deinit();
        allocator.destroy(g);
    }
}

/// Load `cap` layers plus the runtime weights as an independent ModelWeights for
/// the CPU reference. Re-opening the file is simplest and keeps the two paths
/// from sharing any buffer. Works for both model formats.
fn cloneForReference(allocator: std.mem.Allocator, path: []const u8, cap: usize) !model_mod.ModelWeights {
    var mw = if (std.mem.endsWith(u8, path, ".gguf")) blk: {
        var g = try gguf.Gguf.load(allocator, path);
        defer g.deinit();
        break :blk try load_gguf.loadWeights(allocator, &g, false);
    } else blk: {
        var sh = try load_hf.Shards.open(allocator, path);
        defer sh.deinit();
        var hcfg = try hf.loadConfig(allocator, path);
        defer hcfg.deinit(allocator);
        const cfg = try load_hf.toModelConfig(hcfg);
        break :blk try load_hf.loadWeights(allocator, &sh, cfg, false);
    };
    if (cap >= mw.layers.len) return mw;
    for (mw.layers[cap..]) |*lw| lw.deinit(allocator);
    const kept = try allocator.alloc(model_mod.LayerWeights, cap);
    @memcpy(kept, mw.layers[0..cap]);
    allocator.free(mw.layers);
    mw.layers = kept;
    return mw;
}

/// Run the prompt through the first N layers and report the top tokens at that
/// depth, for bisecting a model that produces garbage. `verify` is the sharper
/// tool when the question is "ANE vs CPU"; this one answers "which layer".
fn cmdLayers(allocator: std.mem.Allocator, argv: []const [:0]const u8) !void {
    if (argv.len < 3) {
        sys.eprint("usage: anedvd layers <model> --prompt \"...\" [--upto N]\n", .{});
        std.process.exit(2);
    }
    const path = argv[2];
    const prompt = argStr(argv, "--prompt") orelse "The capital of France is";
    const upto: u32 = argValue(argv, "--upto", 0);

    var loaded = try model_open.open(allocator, path, .{ .progress = false });
    defer loaded.deinit();
    const cfg = loaded.config;
    sys.print("{s}: {d} layers, hidden {d}, heads {d}/{d}, head_dim {d}\n", .{
        cfg.arch, cfg.layers, cfg.hidden, cfg.heads, cfg.kv_heads, cfg.head_dim,
    });

    var eng = try engine_mod.Engine.init(allocator, loaded.rt, loaded.layers, loaded.head, .{
        .max_seq = 256,
        .verbose = false,
    });
    defer eng.deinit();
    if (upto > 0) {
        eng.stopAfterLayer(upto);
        sys.print("stopping after layer {d}\n", .{upto});
    }

    const ids = try loaded.tokenizer.encode(allocator, prompt, true);
    defer allocator.free(ids);
    sys.print("prompt {d} tokens\n", .{ids.len});
    const logits = try eng.prefill(ids, 0);
    const used = try allocator.alloc(bool, logits.len);
    defer allocator.free(used);
    @memset(used, false);
    for (0..5) |i| {
        var best: usize = 0;
        var bv: f32 = -std.math.inf(f32);
        for (logits, 0..) |v, k| {
            if (!used[k] and v > bv) {
                bv = v;
                best = k;
            }
        }
        used[best] = true;
        sys.print("  {d}. id={d} logit={d:.2} {s}\n", .{ i + 1, best, bv, loaded.tokenizer.tokenText(@intCast(best)) });
    }
}
