// ane_shim.h — C-callable bridge to Apple's private AppleNeuralEngine.framework.
//
// This is the only file in the project that touches Objective-C / private APIs.
// Everything above it (Zig) sees a small, boring C ABI.
//
// Design notes (all verified empirically on A18 Pro / macOS 27.0.1 with SIP on):
//   * No CoreML is involved anywhere: MIL text is generated by the caller and
//     compiled by _ANECompiler through _ANEInMemoryModelDescriptor.
//   * Weights are baked at compile time; the weight blob is written into
//     $TMPDIR/<hexStringIdentifier>/ so the ANE daemon can read it.
//   * Tensors are planar: per-channel planes, each plane >= 64 bytes, with the
//     exact strides reported by the loaded model (modelAttributes ->
//     NetworkStatusList[0] -> LiveInputList/LiveOutputList). Callers must use
//     those strides; the ANE ignores nominal dims and uses its own layout.
//   * IOSurfaces are used for zero-copy I/O.

#ifndef ANE_SHIM_H
#define ANE_SHIM_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ANEKernel ANEKernel;

typedef enum {
    ANE_DTYPE_FP16 = 0,
    ANE_DTYPE_FP32 = 1,
    ANE_DTYPE_UNKNOWN = 2,
} ANEDtype;

typedef struct {
    char name[64];
    int dtype;              /* ANEDtype */
    int batches;
    int channels;
    int height;
    int width;
    size_t plane_stride;
    size_t row_stride;
    size_t depth_stride;
    size_t batch_stride;
    size_t nbytes;          /* batch_stride * batches */
} ANETensorInfo;

/* One-time init: dlopens AppleNeuralEngine and resolves the private classes.
 * Returns 0 on success, negative on failure (see ane_shim_last_error). */
int ane_shim_init(void);

/* 1 if init succeeded. */
int ane_shim_ready(void);

/* Human-readable description of the last failure (thread-local). */
const char *ane_shim_last_error(void);

/* Number of ANECCompile() calls made by this process. The ANE daemon silently
 * stops compiling after roughly 120 per process, so callers should cache. */
int ane_shim_compile_count(void);

/* Compile + load an ANE kernel.
 *   mil        : MIL program text (UTF-8)
 *   w_names    : weight file symbols, e.g. "@model_path/weights/w0.bin"
 *   w_data     : weight blob bytes (caller-owned, copied)
 *   n_weights  : number of weight files (max 16 BLOBFILE refs per program)
 *   n_inputs/n_outputs and the declared byte sizes are used only as a hint;
 *   the authoritative sizes come back from ane_shim_*_info() after loading.
 * Returns NULL on failure. */
ANEKernel *ane_shim_kernel_create(const char *mil, size_t mil_len,
                                  const char *const *w_names,
                                  const uint8_t *const *w_data,
                                  const size_t *w_lens, int n_weights);

void ane_shim_kernel_free(ANEKernel *k);

/* Run the kernel once. Returns 1 on success, 0 on failure. */
int ane_shim_kernel_eval(ANEKernel *k);

int ane_shim_input_count(const ANEKernel *k);
int ane_shim_output_count(const ANEKernel *k);
int ane_shim_input_info(const ANEKernel *k, int idx, ANETensorInfo *out);
int ane_shim_output_info(const ANEKernel *k, int idx, ANETensorInfo *out);

/* IOSurface base address for zero-copy I/O. The surface stays mapped for the
 * kernel's lifetime. Callers should hold the lock while writing/reading. */
void *ane_shim_input_base(const ANEKernel *k, int idx);
void *ane_shim_output_base(const ANEKernel *k, int idx);
int ane_shim_input_lock(const ANEKernel *k, int idx);
int ane_shim_input_unlock(const ANEKernel *k, int idx);
int ane_shim_output_lock(const ANEKernel *k, int idx);
int ane_shim_output_unlock(const ANEKernel *k, int idx);

/* Allocated IOSurface capacity in bytes (>= declared nbytes). */
size_t ane_shim_input_capacity(const ANEKernel *k, int idx);
size_t ane_shim_output_capacity(const ANEKernel *k, int idx);

/* Wall-clock time of the last eval in nanoseconds (0 if unknown). */
uint64_t ane_shim_last_eval_ns(const ANEKernel *k);

#ifdef __cplusplus
}
#endif

#endif /* ANE_SHIM_H */
